### ISSUE TITLE
Parser doesn't recognize variables

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#1]
This fails to import:

```
@inproceedings{test_citation1,
  abstract = {Abstract here},
  author = {Doe, J. and Smith, R.},
  booktitle = IEEE_J_PROC,
  doi = {10.1109/JPROC.2016.2526118},
  keywords = {Keyword 1,Keyword 2},
  month = feb,
  pages = {300--301},
  timestamp = {2015-02-24 12:14:36 +0100},
  title = {Test {{Title With}} 100~{{$\mu$J}}, 200\,{{$\mu$J Energy}}, and $\pm$0.1\% {{Accuracy}}, 0.2\,Mm$^2$ {{Size}}, and -50\,{{dB Attenuation}}},
  year = {2016}
}
```

**Comment by johanneswilm** [comment]
@retorquere The biblatex specification says this about the month field:

> The publication month. This must be an integer, not an ordinal or a string. Don’t
say month={January} but month={1}.

Is this maybe standard bibtex? Is there a specification for this somewhere? Or what's the source of this?

**Comment by retorquere** [comment]
This input file is standard BibTeX; my parser needs to be tolerant of both.

**Comment by retorquere** [comment]
But the parser fails on the undeclared variable in `booktitle = IEEE_J_PROC,`

**Comment by johanneswilm** [comment]
I see. The parser throws a warning, but does process the rest of the entry for me. 

What you want is to be able to declare a variable like this?

> @string{IEEE_J_PROC = "IEEE J PROC Title"}

**Comment by retorquere** [comment]
Your parser already handles that; this parses OK:

```
@String{pub-FRED = "Freds Publishing"}
@String{pub-FRED:adr = "London, UK"}

@Book{Bert:2001:SQL,
  author = "R. A. Bert",
  title = "SQL is great",
  publisher = pub-FRED,
  address = pub-FRED:adr,
}
```

it's just that when a var is not declared, the parser fails. Perhaps that's a good thing, but how do I get the error rather than it being simply output on the console?

**Comment by johanneswilm** [comment]
Yes, it does.

Well, the parser doesn't fail. It just gives a warning. It still gives you valid output. For other errors there is an array of errors that you can find at parser.errors. I will move those that gave console warnings there as well. That way you can process them more easily.

**Comment by retorquere** [comment]
I see. Can the console logging be suppressed? It makes it harder for me to see what I output in my tests.

**Comment by johanneswilm** [comment]
That should do what you want. I also added an entry into the FAQ to make it more obvious.

**Comment by retorquere** [comment]
Super, that makes my testing a lot easier.
