### ISSUE TITLE
Unparsed fields from my test suite

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#11]
I've just ran through all my test files, and this is the list of fields that the parser flags as errors. Some of these clearly are bogus, but these are all references from the field.

* collaborator
* keywords
* owner
* timestamp
* comment
* numpages
* adsnote
* adsurl
* refid
* nationality
* yearfiled
* day
* dayfiled
* monthfiled
* review
* options
* langid
* rights
* xref
* crossref
* biburl
* description
* ee
* groups
* interhash
* intrahash
* bibsource
* director
* scriptwriter
* pmid
* affiliation
* author-email
* doc-delivery-number
* funding-acknowledgement
* funding-text
* journal-iso
* keywords-plus
* number-of-cited-references
* subject-category
* times-cited
* usere
* presort
* related
* relatedtype

**Comment by johanneswilm** [comment]
Yes, these are not defined in biblatex. That doesn't mean we shouldn't support them, but we need to have some kind of spec for them. I assume that several of these could be declared as aliases for existing fields?

**Comment by retorquere** [comment]
`collaborator` is a proper biblatex field but not all of the above are of course. I'd be happy enough if properly structured fields that are non-standard showed up under something like `other` rather than `fields`.

I see that `fields` is an object BTW, which means that each field can show up only once, but there are a few fields that can appear more than once. From memory, at least `annotation` and its aliases, and `file` and its aliases.

**Comment by johanneswilm** [comment]
>  I'd be happy enough if properly structured fields that are non-standard showed up under something like `other` rather than `fields`.

That should be doable. Currently it gives all fields, and I  don't think it checks whether the corresponding bibtype lists the field under required or optional or not at all. I would like to be stricter there, but then these extra fields could go into `other fields` as you say. There should probably still be an error, but if you don't mind it not following the standard, you can just ignore all the errors of that one type.

The only thing is that for fields that are completely unknown to the system, it will only be able to give you the raw input string, as it won't know how to parse it.

> I see that `fields` is an object BTW, which means that each field can show up only once, but there are a few fields that can appear more than once. From memory, at least `annotation` and its aliases, and `file` and its aliases.

Can you find some info about this? I could not find anything about it under annotation or file in the biblatex doc.

**Comment by retorquere** [comment]
The biblatex manual doesn't say explicitly one way or the other, but again here, I go with what people have brought me. Perhaps @njbart knows -- he often drops in on BBT, he seems to know a lot about this -- certainly heaps more than me.

I'd prefer that the `other` files be parsed as if they were literals. The parser needs to go through them in any case so find the next field, and for unsupported fields literal seems a safe enough choice.

**Comment by njbart** [comment]
> ... fields that can appear more than once ...

No, I don't think so. If in doubt, try it out with latex/biblatex (the programs).

**Comment by johanneswilm** [comment]
> I'd prefer that the `other` files be parsed as if they were literals. The parser needs to go through them in any case so find the next field, and for unsupported fields literal seems a safe enough choice.

Ok, so that would basically mean they get style parsing, but not case preservation, splitting up, etc. . That should be doable.

**Comment by retorquere** [comment]
Correct, that'd be the easiest for me to deal with.

**Comment by johanneswilm** [comment]
All fields are now available under raw_fields. Additionally, if we know the fieldtype, they can be found in a processed state either under "fields" if defined for the given bibtype, or under "unexpected_fields" if not defined.

**Comment by johanneswilm** [comment]
That leaves us with the issue on the field ```collaborator```. In the biblatex manual I can only find that term as an "editorial role", but not as a field type. Is it ok if we don't add that field?

**Comment by retorquere** [comment]
I think I've misexplained myself; I don't actually need the raw fields as raw LaTeX, but as original field name mapped to "cooked LaTeX". The `unexpected_fields` will do for me from what I can tell. The `alias` errors will have the cooked value, right?

I don't mind where the role is stored, but I do need to know which creators are collaborators. Collaborator is a supported type of creator in Zotero (even though I think Zotero displays it as "contributor"), so if I get collaborators I need to be able to map that one way or the other.

**Comment by retorquere** [comment]
(on export, I export collaborators as `editora` and set `editoratype` to `collaborator`. Something similar is done for `redactor`)

**Comment by johanneswilm** [comment]
> I think I've misexplained myself; I don't actually need the raw fields as raw LaTeX, but as original field name mapped to "cooked LaTeX". The `unexpected_fields` will do for me from what I can tell. The `alias` errors will have the cooked value, right?

OK, but `unexpected_fields` only gives fields that we know, but that are not defined for the current bibtype.

What you want is to process the latex in all fields -- and that is a little problematic, because it's costly.

I was thinking we could add a few configuration settings on:

1. whether to process unexpected fields (according to their type).
2. whether to process fields that are entirely unknown (as literals).

In FW we could set it to off, and you could set these to on.

> I don't mind where the role is stored, but I do need to know which creators are collaborators.

ok, so do you want to store the field on an empty editor* field and have the editor*type set to collaborator? What if there are no more slots?

**Comment by retorquere** [comment]
As I said, the unexpected_fields will do the job for me. "defined for the current bibtype" will have to include BibTeX behavior for BBT BTW, not only BibLaTeX behavior.

I'm perfectly fine with making this a switching behavior. Processing cost is less important to me than completeness of recovery; import happens infrequently in BBT, and I cache results heavily.

I honestly don't mind where the role is stored; it could be added as a `role` to the individual creators for example, or editor*, or anything, as long as I can deterministically derive that it was once a collaborator on import.

**Comment by johanneswilm** [comment]
> As I said, the unexpected_fields will do the job for me. 

OK, but unexpected_fields only holds fields that were in the regular fields a few hours ago (when you filed this issue). The fields this bug report was originally about are still only available in the raw_fields with no processing beyond the tex character replacement..

> "defined for the current bibtype" will have to include BibTeX behavior for BBT BTW, not only BibLaTeX behavior.

What FW needs is an authoritative list for each bib entry type. We use the same definition for the web form. So if a user wants to edit or create an entry of type "book", the user is presented with the required and optional fields for the "book" type. We can extend the list of optional and required fields for certain entries, but I would be opposed adding fields that more or less mean the same, and I think the biblatex team has done a fairly good job of removing those or declaring them aliases of existing fields.

So I think there re several options here:

1. We extend the definition with some extra fields that we don't currently have and that the biblatex team for whatever reason left out.

2. We write a second list of field definitions for bibtex.

3. We add a config option to process all unknown fields (as literals).

**Comment by retorquere** [comment]
For BBT, option 3 would suffice.

**Comment by johanneswilm** [comment]
Ok, see the faq in the readme for how to use the config options. You can even use it to process "collaborator" as a name.
