### ISSUE TITLE
Unrecognized referencetypes from my test suite

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#12]
* jurisdiction
* legislation
* letter
* video
* movie
* archived
* data
* audio
* review

**Comment by johanneswilm** [comment]
I see several of these are listed in the "unsupported" section of the biblatex manual. Maybe we can define what kinds of fields these should have (required) and which ones they can have, or whether thye are aliases for existing types...

**Comment by retorquere** [comment]
If they're named as unsupported, that means they most likely at some point were, or were always unsupported but still prevalent enough that they made it into the manual. In either case I need to do something with these.

**Comment by johanneswilm** [comment]
>  I need to do something with these.

Ok, the question is then what that "something" is.  :) Could you maybe define what fields should be connected with these or whether they are aliases, etc.?  If we have that, we can treat them like other types. Also, if they have equivalents in CSL, we should capture that in https://github.com/fiduswriter/biblatex-csl-converter/blob/gh-pages/src/const.js

**Comment by retorquere** [comment]
I map them; if I can make nothing sensible of it, it goes to `journal article`. For fields of these I just fall back to basic processing -- `title`ish fields go to the Zotero title, `author` goes to creator, etc. Remember my aim is just to get the reference into Zotero -- making biblatex out of it again is a wholly separate task in BBT.

**Comment by johanneswilm** [comment]
The parser does register everything it doesn't understand as "misc". It just throws the error so you are aware that it doesn't get it. This is following biblatex rules, AFAICT

```
2.1.3 Unsupported Types
The types in this section are similar to the custom types @custom[a--f], i. e., the
standard bibliography styles provide no support for these types. When using the
standard styles, they will be treated as @misc entries.
```

It's only if you believe you need to do something more than that with these types that we need to add code.

**Comment by retorquere** [comment]
Ah. Hmm. No, I suppose this will do, at least until I meet an issue that would need it. Can't think of any right now.

**Comment by johanneswilm** [comment]
Great!
