### ISSUE TITLE
'alias_creates_duplicate_field': include aliased field

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#19]
For reporting & debugging it'd be nice to know what field it aliased, and to have access to its value.

**Comment by johanneswilm** [comment]
ok, this should give you the name of the original field. Unfortunately the way it's set up, it's difficult to give you the raw value of the original field. If it's very needed, I'll need to refactor a bit.

**Comment by retorquere** [comment]
I don't need it raw, this will do.
