### ISSUE TITLE
distinguish between warnings and errors

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/biblatex-csl-converter#22]
**Errors** should only be things that mean that a field or entry is ignored entirely.
**Warnings** should merely notify when there is something unexpected (for example an unknown bib entry type is imported, so it is saved a a misc).

How about warnings/errors when unknown/unexpeccted fields are encountered? What if the user specifies he wants these fields? SHould there still be an error? A warning? Or maybe a third level (info notification)?

@retorquere You spoke earlier about warnings and error. Is this the distinction you were thinking about?

**Comment by retorquere** [comment]
I was thinking that `year` having a non-year value would be cause for a warning. It's within spec, so it's not an error, but even the manual basically says "please people, don't"

**Comment by retorquere** [comment]
And variable_error.

**Comment by johanneswilm** [comment]
Should they all come in the same array with a flag "warning" or "error", or should there be two different arrays?

**Comment by retorquere** [comment]
No preference between the two, whatever's easiest to do.
