### ISSUE TITLE
\_ not parsed correctly

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#23]
`title = {bugreports\_{{ApostropheOnParticle}}}`

is translated to

`bugreports<sub><span class="nocase">ApostropheOnParticle</span></sub>`

rather than

`bugreports_<span class="nocase">ApostropheOnParticle</span>`

**Comment by johanneswilm** [comment]
This is because someone added these basic characters to the translation table :)

```
 ["\\\\_", '_'],
```

I'll remove those basic ones again.

**Comment by retorquere** [comment]
The bastard. I've added the exception to the generation script to be sure.
