### ISSUE TITLE
\vphantom\{ should be ignored

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#24]
In fact `\vphantom<latex construct>` should be ignored, but for BBT purposes, `\vphantom\{` will do. BBT generates `\vphantom\{` to compensate for a [bug in an older biber version](http://tex.stackexchange.com/questions/230750/open-brace-in-bibtex-fields/230754#comment545453_230754) which would break on `title = {Aesthetic {{Judgment}}\}}`, but not on `title = {Aesthetic {{Judgment}}\vphantom\{\}}` (which render to the same).

**Comment by johanneswilm** [comment]
Should this be in the tex char table then?

**Comment by johanneswilm** [comment]
current it's being destroyed by:

["\\\\v", '\u030C'],

**Comment by retorquere** [comment]
That is one approach; my parser just recognizes `\vphantom<latex construct>` and returns an empty string. It would ignore `\vphantom+` and `\vphantom{long and boring comment about becoming oneself, which is a weird statement that seems to ignore the law of identity}` too.

But as I said, I have only ever seen it used in bibtex to work around that single bug.

**Comment by johanneswilm** [comment]
Ok, but currently it never gets to that, because the above rule does that the `\v` is being removed. Would that not happen, the styler would remove it because it's a non-recognized command.

So before replacing `\v`, we ned to remove `\vphantom`.

**Comment by retorquere** [comment]
Definately also the LaTeX construct behind it. In the case of `\vphantom\{`, `\{` is the construct to be removed. `\vphantom{\{}`ought to also be removed on a full implementation, as `{\{}` is a single construct -- but again, I've not seen this in actual BibTeX.

**Comment by retorquere** [comment]
I guess what I mean that vphantom is more like markup than a separate command. If vphantom would be parsed into a `<del>` tag I can take it from there.

**Comment by johanneswilm** [comment]
Sorry. I removed it entirely, as that's what I thought you were asking for. `<del>`-tags don't exist in CSL, right? How is it being used by users in bibliographies other than to get around a bug in an old version of biber?

**Comment by retorquere** [comment]
This is fine too. I know of no other usage of this in bibliograpy.
