### ISSUE TITLE
escaped braces ignored, text cut short

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#26]
`({{Liquid}}+liquid) Equilibrium of {{\{water+phenol+(1-butanol, or 2-butanol, or tert-butanol)\}}} Systems`

is parsed to

`(<span class="nocase">Liquid</span>+liquid) Equilibrium of <span class="nocase">water+phenol+(1-butanol, or 2-butanol, or tert-butanol)</span>`

rather than (something like)

`(Liquid+liquid) equilibrium of <span class="nocase">{water+phenol+(1-butanol, or 2-butanol, or tert-butanol)}</span> systems`

**Comment by johanneswilm** [comment]
The reason being:

```
 ["\\\\\\}|\\\\rbrace", '}'],
 ["\\\\\\{|\\\\lbrace", '{'],
```

**Comment by retorquere** [comment]
I don't understand? Those should recognize them and replace them, right? Or do you mean you don't want `\\\\\\}` and handle those separately?

**Comment by johanneswilm** [comment]
Yes, first the tex char replacements are applied. After that the literal field style handler is run. For it to run correctly, it still needs it to be valid latex code with escaping and all. Otherwise the styling will misunderstand what's going on.

**Comment by retorquere** [comment]
Ah, I see. This is a two-stage parser, mine is a one-stage parser. I was doing the command -> unicode at the same time as the structure parsing.

**Comment by retorquere** [comment]
The fix works BTW.
