### ISSUE TITLE
\LaTeX is not parsed

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#27]
I don't really know what \LaTeX should be parsed to. Perhaps just LaTeX, or a combination like L$^A$T$_E$X. But right now it parses to łatex

**Comment by johanneswilm** [comment]
How will this be inserted? There is html in pretags in the input bibtex?

**Comment by retorquere** [comment]
These would be entered manually by the user.

**Comment by johanneswilm** [comment]
so this is only in the output? Or where is this?

**Comment by retorquere** [comment]
That's just me being dense, sorry.

**Comment by retorquere** [comment]
I don't really know what `\LaTeX` should be parsed to. Perhaps just `LaTeX`, or a combination like `L$^A$T$_E$X`. But right now it parses to `łatex`

**Comment by retorquere** [comment]
(that looks really funny now 😄 )
