### ISSUE TITLE
Name particles

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#30]
Right now,

`author = {Aubignac, abbé d', François Hédelin},`

parses to

`[{"lastName":"Aubignac  abbé d'","firstName":"François Hédelin"}]`

I didn't do much better with my own parser, but do keep in mind that CSL will expect to see `abbé d` reported as a dropping or non-dropping particle rather than part of a name part. The BBT name generator, which generates Bib(La)TeX names from how they're stored in Zotero (which is why you see `lastName` rather than `family` in my name reports, sorry), is pretty involved and uses the citeproc name parser for part of the work.

**Comment by johanneswilm** [comment]
The way I read it, CSL json seems to allow both for splitting it into two or four parts. If this is incorrect, we can switch to four parts as well.

**Comment by johanneswilm** [comment]
> The CSL-JSON allows some flexibility about how parts of a person’s name are encoded. For instance, family name affixes such as “van” and “de las” can be encoded as part the family name in the “family” property. Likewise, suffixes such as titles, generational designations, credentials, and honors can be encoded as part of the given name. Generational designations (like “Jr” or “IV”) immediately follow the given name without a comma. All other suffixes should follow next, with each suffix preceeded by a comma.

http://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#person-field-type

**Comment by johanneswilm** [comment]
I read the name parser or exporter that you used from zotero last summer. I believe I could tell that it was better at some tasks and worse at others than the one we use.

**Comment by retorquere** [comment]
That's true, but in the sample above, it should be presented to CSL as

`[{"family":"Aubignac","given":"François Hédelin, abbé d'"}]`

instead of

`[{"family":"Aubignac abbé d'","given":"François Hédelin"}]`

**Comment by retorquere** [comment]
My bibtex name parse is stupid. The good name parser I have is the one that deals with Zotero names.

**Comment by johanneswilm** [comment]
ok, so `abbé d'` is part of the firstname?

**Comment by retorquere** [comment]
Not really, it's a name particle, but citeproc will understand it if you put it there. Whether the particle goes in the given or family name depends on whether it's a dropping or a non-dropping particle.

biblatex supports another format for names btw that makes things even harder. My own parser doesn't understand it, but BBT will generate it if you have a name with particles in Zotero: https://github.com/retorquere/zotero-better-bibtex/issues/566

**Comment by retorquere** [comment]
I don't mean the parser should understand all this. Names are friggin hard. I think this will be mainly relevant for the CSL output. My current parser does a half-assed attempt at importing names and expects the user to correct them in Zotero to have them formatted in a way that I can parse them (sort of) cleanly.

I have no doubt that my current import parser will generally do worse than yours, to be honest. But I'd be *really* surprised if the current state of the library generates better quality output, both biblatex and CSL.

**Comment by johanneswilm** [comment]
Yeah, just found the list:

https://gist.github.com/gracile-fr/ed650f9ca31faf8f671c

What we could do would be to store more different parts than given and family internally. if that would be of help.  But it seems we can only take an educated guess what the user tried to express anyway.

**Comment by johanneswilm** [comment]
I think our name parser tries to follow this:


> To summarize, you may type a name in one of three forms:
>
> "First von Last" "von Last, First" "von Last, Jr, First"


http://nwalsh.com/tex/texhelp/bibtx-23.html

So it's assuming that the field in question is the "Jr" part. 

But still then, the output is not perfect. Would CSL like something like:

```
{family: 'Bush, Jr.', given: 'George'}
```

?

**Comment by retorquere** [comment]
I think that list is outdated. citeproc tried to use an authoritative list but that git cumbersome very quickly -- I think they currently have something like

* particles are all trailing all-lowercase words
* a particle is dropping if it is in the given name, non-dropping if it is in the family name

Note BTW that for biblatex you need to account for the spaces needed/present for DeclarePrefChars.

**Comment by retorquere** [comment]
(and yes, to my knowledge, the middle part is the so-called comma-suffix -- you may want to output `juniorcomma=true` if one is present)

In any case, I'd have expected `author = {Aubignac, abbé d', François Hédelin}` to be parsed as if `abbé d'` was a comma-suffix, and expect the parsed result to have a comma present in the family name.

Names are really, really tricky.

**Comment by retorquere** [comment]
(I am not an expert on what CSL expects. Frank Bennet would be that person, but he has very limited time available for discussion)

**Comment by johanneswilm** [comment]
Ok, so if we parse

```
Bush, Jr., George
Aubignac, abbé d', François Hédelin
```

to

```
{given: 'George', family: 'Bush, Jr.'}
{given: 'François Hédelin', family: 'Aubignac, abbé d''}
```

Would that seem like a reasonable way of dealing with it?

**Comment by retorquere** [comment]
One of the more tricky ones (I think) was this:

`author = {von Humboldt, Alexander and Gooding, Jr., Cuba and de La Fontaine, Jean and von Wright, Georg Henrik Auto and {von Wright}, Georg Henrik Explicit}`

For these authors:

1. CSL will expect [Humboldt][Alexander von] to make the `von` dropping
2. Will expect the `Jr` to turn up (I think) in the last name but separated with a comma
3. CSL will expect [La Fontaine][Jean de]
4. is parsed OK
5. CSL will expect ["von Wright"][Georg Henrik Explicit] (including those quotes)

quoted names are sort of like case protection in names, but that is specific to CSL and tools that use it (pandoc/Zotero/Mendeley/others)

**Comment by retorquere** [comment]
I think those look reasonable.

**Comment by retorquere** [comment]
correction: CSL will expect `{Bennett, Jr., Frank G.}` as `[Bennett][Frank G.,! Jr.]` (the `,!` makes it a comma-suffix I think)

**Comment by retorquere** [comment]
Or it doesn't maybe expect it, but `,!` forces it to treat it as comma suffix. Or something.

Names are friggin hard.

**Comment by johanneswilm** [comment]
> correction: CSL will expect `{Bennett, Jr., Frank G.}` as `[Bennett][Frank G.,! Jr.]` (the `,!` makes it a comma-suffix I think)

Ok, what does it do if it isn't there?

> quoted names are sort of like case protection in names, but that is specific to CSL and tools that use it (pandoc/Zotero/Mendeley/others)

So maybe quote output in CSL = extra brackets in biblatex? (I did see that there needs to be a space in biblatex between `'` and `{`

**Comment by retorquere** [comment]
When not present it tries to guess. I'm not entirely sure.

The space behind punctuation has to to with DeclarePrefChars. `author = {al- One, Alan}` should parse to `[al-One][Alan]`.

**Comment by johanneswilm** [comment]
> When not present it tries to guess. I'm not entirely sure.

OK, but so are we. And chances are that citeproc has more advanced mechanisms for guessing, or not?

> The space behind punctuation has to to with DeclarePrefChars. `author = {al- One, Alan}` should parse to `[al-One][Alan]`.

So this applied to what characters? `-`, `'`  -- what else? Basically these need to be removed when parsing and added when exporting, right?

**Comment by retorquere** [comment]
And yes, quotes in CSL names correspond somewhat to extra braces in bibtex, but the quotes can only be on the whole namepart, where braces can in principle appear anywhere.

I really don't know in any detail how CSL name parsing works.

The default DeclarePrefChars are `'’-`. a space after those should be removed on parsing (if in a particle, I suppose, but where else would we find them), and added on output (but *only* after a particle; `Plunkett-Ernle-Erle-Drax` should not get spaces)

**Comment by johanneswilm** [comment]
> One of the more tricky ones (I think) was this:

> `author = {von Humboldt, Alexander and Gooding, Jr., Cuba and de La Fontaine, Jean and von Wright, Georg Henrik Auto and {von Wright}, Georg Henrik Explicit}`

> For these authors:

> 1. CSL will expect [Humboldt][Alexander von] to make the `von` dropping

Ok, but why do we assume it's dropping when the author put it in the last name? If it were to be dropping, wouldn't the author have written "Humboldt, Alexander von"?

> 2. Will expect the `Jr` to turn up (I think) in the last name but separated with a comma

ok

> 3. CSL will expect [La Fontaine][Jean de]

Again, why did the author put it in the last name field if is to be dropping? `de` can be either dropping or non-dropping, as far as I can tell.

> 4. is parsed OK
> 5. CSL will expect ["von Wright"][Georg Henrik Explicit] (including those quotes)

Those are ok.

**Comment by retorquere** [comment]
> Ok, but why do we assume it's dropping when the author put it in the last name? If it were to be dropping, wouldn't the author have written "Humboldt, Alexander von"?

Because CSL and biblatex each have their own particle parsing algorithms. CSL expects [Humboldt][Alexander von], but biblatex expects {von Humboldt, Alexander}, to get (roughly, this is too complex for me to know all the details) the same behavior qua rendering and sorting.

"de" can indeed be dropping or non-dropping. CSL just follows the rule "dropping if in given name, non-dropping if in family name".

**Comment by retorquere** [comment]
@njbart is my go-to guy when it comes to these matters where it involves bib(la)tex; @fbennett for CSL. I really can't speak authoritatively on either of them, I just go through my issues and test cases and the occasional rendered MWE and go by those.

**Comment by johanneswilm** [comment]
OK, I see. Looking at this [1], we should probably also parse the extended form of names in biblatex. Confusion only exists in the "traditional" format where it's not clear what is what, right?


[1] https://github.com/retorquere/zotero-better-bibtex/issues/566

**Comment by johanneswilm** [comment]
I'd be OK with adding two extra fields: `particle` and `suffix` and possible a true/false for dropping/non-dropping. That should make export better, and also importing the new bibtex format should not be too difficult. But for import from the traditional bibtex/biblatex format, I'm not sure what to do. We can find suffix, firstname and lastname. 

For the particle, do we simple take 1-2 lowercase words that come at the start of the lastname? We'll assume it's dropping, unless it's inside braces together with more text?

**Comment by retorquere** [comment]
Correct, the new format is as unambiguous as it gets for biblatex name parsing. I don't expect it is widely in use yet, but it's clearly the better option.

I think what you say about particles describes how citeproc approaches is. Any sequence of all-lowercase words at the end of a name part is a particle; if in the given name, dropping, if in the family name, non-dropping.

**Comment by johanneswilm** [comment]
> I think what you say about particles describes how citeproc approaches is. Any sequence of all-lowercase words at the end of a name part is a particle; if in the given name, dropping, if in the family name, non-dropping.

And for biblatex?

In your example:

> `author = {von Humboldt, Alexander and Gooding, Jr., Cuba and de La Fontaine, Jean and von Wright, Georg Henrik Auto and {von Wright}, Georg Henrik Explicit}`

The "von" in "von Humboldt" and "de" in "de La Fontaine" are droppable because they are not in protective braces? Whereas the "von" in "von Wright" is non-droppable because it does have braces?

If we use these extra fields, do we still need to add the braces for CSL?

**Comment by retorquere** [comment]
for biblatex I have no idea what the rules are, but here's what BBT produces, which according to people more knowledgable than me works out OK. The best option is of course to use the extended name format and BBT will produce that (but not parse it at this time) if you have it enabled. Otherwise, assuming I have an object with optional members `family`, `given`, `dropping-particle`, `non-dropping-particle`, `suffix`:

* if `family` starts with a lowercase letter, assume it needs protection and wrap it with braces
* if the user has placed an initials marker (`'\u0097'`, but this is BBT-specific) in `given` , so e.g. `Ph\u0097ilippe`, put in a `\relax` (`{\relax Ph}ilippe`)
* add a space to the particles unless there already is a space at the end
* `family` = `dropping-particle` + `non-dropping-particle` + `family` (parts not present skipped)
* join [family, suffix, given] with a comma (parts not present skipped)

BibTeX production is a little more complicated. Not much, but more edge cases.

Your analysis sounds correct, but I really don't know the rules. EIther @njbart admonishes me for getting it wrong, or I do trial and error with MWEs to see what happens.

**Comment by retorquere** [comment]
I don't know whether there are CSL cases that require quotes that cannot be solved otherwise.

**Comment by johanneswilm** [comment]
Ok, but in this case we'd need to remove the braces if we want to split the two in two different fields, right?

**Comment by johanneswilm** [comment]
From the description of https://github.com/retorquere/zotero-better-bibtex/issues/566 I gather that on this particular planet there are no names with both a dropping and a non-dropping particle, even though citeproc allows it.

Combining that with your description of how you export bibtex, it sounds like it's ambigious and there is no way to differentiate between the two in traditional bibtex entries.

**Comment by retorquere** [comment]
Names are friggin hard.

**Comment by johanneswilm** [comment]
Ok, so the result of this will be:

* we'll add three extra fields: `prefix` (string), `suffix` (string) and `dropping` (true/false)

* the traditional biblatex/bibtex name format does not specify whether or not it's dropping. So for those all entries will get the default value (which is true or false?)

* the parser will be made to also accept the new biblatex name format

* the biblatex exporter will get a config option to output the new format (not relevant for you for now)

Do we also need an extra field for the junior-comma? Or can this be derived automatically from the existence of a "Jr" string in the suffix-field?

**Comment by johanneswilm** [comment]
> The space behind punctuation has to to with DeclarePrefChars. `author = {al- One, Alan}` should parse to `[al-One][Alan]`.

Does this also apply to the extended name format?

**Comment by johanneswilm** [comment]
Actually, this space is only between the lastname and the prefix/particle, right? So as long as we keep the particle in a separate field, and trim it, we don't have to worry about the space, do we?

**Comment by retorquere** [comment]
Yes, it's only between the particle and the last name
