### ISSUE TITLE
Reference hangs parser

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#36]
When I try to parse these references, the parser hangs

```
@article{bentley_academic_2011,
  abstract = {State planning has been a defining means for modern subjects to regulate the passage of time. In practice, it is the focus of multiple conflicts and doubts, which planners attempt to mediate. In this paper, I address the regimes of time that planning both promotes and encounters, and tease out what these imply for anthropology. Using ethnography of Norwegian and Swedish planning offices and their encounters with participatory planning, I question recent claims that there has been an evacuation of the near future or a retreat of administrative intervention. I also suggest that recent anthropological concerns with time have been confined by their attempts to characterize the changing timescapes of specific modal shifts, such as from the modern to the neoliberal. Instead, in my ethnography, I focus not on tracking epochal breaks in time, but on demonstrating how time is manipulated, and how multiple temporalities are performed in ongoing projects of democratic planning.},
  annotation = {This is the child note},
  author = {Abram, Simone},
  doi = {10.1111/1467-9655.12097},
  issn = {1467-9655},
  journaltitle = {Journal of the Royal Anthropological Institute},
  keywords = {måske},
  langid = {english},
  pages = {129--147},
  rights = {© Royal Anthropological Institute 2014},
  shortjournal = {J R Anthropol Inst},
  shorttitle = {6~{{The}} Time It Takes},
  timestamp = {2015-02-24 12:14:36 +0100},
  title = {6~{{The}} Time It Takes: Temporalities of Planning},
  url = {http://onlinelibrary.wiley.com.ep.fjernadgang.kb.dk/doi/10.1111/1467-9655.12097/abstract},
  urldate = {2014-12-27},
  volume = {20},
  xref = {welker_andreas_1999},
  year = {[2014]}
}

@article{pollard_bicycle_2007,
  author = {Pollard, A. Mark and Bray, Peter},
  journaltitle = {Annu. Rev. Anthropol.},
  pages = {245--59},
  shortjournal = {Annu Rev Anthr.},
  timestamp = {2015-02-24 12:14:36 +0100},
  title = {A Bicycle Made for Two? {{The}} Integration of Scientific Techniques into Archaeological Interpretation},
  url = {http://www.annualreviews.org/doi/pdf/10.1146/annurev.anthro.36.081406.094354},
  volume = {36},
  year = {[2007]}
}

@jurisdiction{kartinyeri,
  author = {Kaetinyeri v Commonwealth},
  date = {1998-04-01},
  institution = {{HCA}},
  journaltitle = {CLR},
  keywords = {au},
  pages = {337},
  shorttitle = {Kartinyeri},
  timestamp = {2015-02-24 12:14:36 +0100},
  title = {Kartinyeri v {{Commonwealth}}},
  translator = {Kartinyeri},
  volume = {195}
}
```

**Comment by retorquere** [comment]
Likewise for

```
@article{test-ticket1661,
  title = {non-braking space: ~; accented characters: {\~n} and \~{n}; tilde in URL: \url{http://example.com/~user}}
}
```

**Comment by retorquere** [comment]
I've been able to trace the roblem into StringParser, but there it gets a little muddy for me.

In that code I see that `%` triggers some kind of variable handling? I thought that in a bibliography, `%` just meant `%`.

**Comment by retorquere** [comment]
Is there a specific reason to hand-build a parser rather than use jison/pegjs? I must admit I'm struggling with the parser code.

**Comment by johanneswilm** [comment]
Well, mainly it's that it is more flexible and easier to read. But I would have been willing to switch to pegjs as well, if you want to do that. It probably would mean that I wouldn't be able to fix anything or only small things, but if you are willing to maintain it, I would be ok with it.

I am wondering whether the solution to this may be to find all the URLS and other fields that should not have their contents be influenced by tex char code replacement  (= verbatim fields) first and create a dict with their contents, and replace the URLs with placeholders in the contents. Then do the char code replacement, and finally reinsert the url contents when one runs into them during literal parsing.

**Comment by retorquere** [comment]
Flexible, sure, but easier to read... I'm struggling to get a clear overview. But pegjs, while (I think), would be easier to read, it's probably a lot slower than either a manual parser or jison. The current BBT parser is pegjs, but I think the manual one has to be faster.

Not really a major issue for me one way or the other, but for me the reasoning is the same but exactly opposite: I'd be capable of fixing small things, but changing the parser would be very hard for me, as I don't really know how it is put together, and I don't have a birds-eye-view.

Given that situation, it's better to keep it as it is. The parser is nearly done now, and it's better than mine currently is.

**Comment by johanneswilm** [comment]
> But pegjs, while (I think), would be easier to read, it's probably a lot slower than either a manual parser or jison. The current BBT parser is pegjs, but I think the manual one has to be faster.

OK, yeah I couldn't figure out what was going on in the current parser. But probably I have just read this code so much now that it all seems very familiar. I would be more than happy to change things though, if it makes it easier for you.

**Comment by retorquere** [comment]
I was just wondering about the way you got to this parser. I'm comfortable with pegjs, but it's known to be slower than things like jison (and I have good reason to suspect the current parser would be at least on a par with jison). I can read and fix jison just fine but cannot write it from scratch, so that's a non-starter. If someone were to come along and offer a jison parser I'd be all for it (the whole model of the parser easily fits my mental state so it'd be easier to reason about), but I get a sense you care about performance, and pegjs is easy but slower than what you have now.

**Comment by retorquere** [comment]
(oh you mean *my* current parser? yeah that needs urgent refactoring. Part of the code lives wholly outside the parser in a companion lib written in coffeescript that is spliced in. coffeescript is going out as soon as I have the 5.0 port done. I'm likely going with ES6, but I may consider typescript)

**Comment by johanneswilm** [comment]
Yeah, history of this is something like this:

2010: Henrik Muehe creates bibtex parser in JS, stops maintaining it right afterward
2012: FW needs bibtex parser, takes Muehe's code and extends it with biblatex functionality. The programmer who worked on it, Takuto Kojima, first had a parser in the python backend, and when we make the switch due to performance reasons, a lot of the parsing that wasn't included with Muehe's javascript project ( fx name parsing, etc.) stays in the backend.
2013-16: You and others send in a lot of bug reports. first Takuto, then I fix a lot of code both in python and javascript.
2016: Finally I decide to move it all to Javascript, to be able to maintain it better as a separate project. It takes a lot of wrangling with the FW code, and I'll still have to do a lot to make it fit.

Apart from that:
2013: Mikola Lysenko takes Henrik Muehe's code form 2010, moves it to commonjs
Summer 2016: RC Peters from Orcid takes Lysenko's code and makes it work with nodejs, someone adds support for endnote: https://github.com/ORCID/bibtexParseJs

So suddenly we have two projects that are somewhat similar in code structure. I contacted RC Peters yesterday and he is interested in merging.
