### ISSUE TITLE
value in "unknown_field" warning

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#37]
For BBT I'd need the cooked value in "unknown_field" warnings, as I'll try to import those into loosely matching fields.

**Comment by johanneswilm** [comment]
It will give you the cooked value in the entry if you turn processUnknown on in the config.

**Comment by johanneswilm** [comment]
Cooking the value is rather expensive. Which is why it's turned off by default for unknown fields. For what you want to do, it seems you should turn unknown fields on and then iterate over those rather than the warnings.
