### ISSUE TITLE
Immediately consecutive runs with the parser yield differing output

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#39]
I have no idea what's going on. If I uncomment [this line](https://github.com/fiduswriter/biblatex-csl-converter/blob/master/test/fixtures-import.js#L23), a run of the tests will replace the "expected" output (which will then be read in immediately, and the test will predictably pass). But if you then re-comment that line and immediately run the test suite again, some of the tests fail. This means the parser result isn't deterministic, but damned if I know how this can be.

**Comment by johanneswilm** [comment]
hmm, have you tracked down the files this is in?

**Comment by johanneswilm** [comment]
Could this have something to do with ava tests being run simultaneously on different threads?

**Comment by johanneswilm** [comment]
Have you tried diffing the output?

**Comment by johanneswilm** [comment]
I uncommented it, ran it, and my laptop crashed.

**Comment by retorquere** [comment]
That could be a coincidence. That lines doesn't do anything special, it just dumps an object it already has to disk. But I've noticed that after a few test runs, I have several lingering node processes and my laptop slowed to a crawl, to the point I had to forcefully reboot because it went unresponsive. For me it didn't matter whether that line was active or not.

I can't exclude it being due to ava running multiple threads, but I don't see a way it could result in this variability. The fixtures runner is fully sync. I don't know how they would affect each other.

Currently it is even weirder. If I comment out those lines, I would expect the checked-in json files to show up in a diff, but they don't. So that'd mean nothing changes on that run, yeah? But if I disable the line again, my tests fail -- and as far as I can tell, always the same tests. I've attached a failing run. I'm at a loss here.
[typescript.txt](https://github.com/fiduswriter/biblatex-csl-converter/files/620365/typescript.txt)

**Comment by johanneswilm** [comment]
Yes, it seems like that there is a difference when using file write.

I noticed that this happens with several files that have both a bibtex and a biblatex version. Could it be that the setup at random chooses which one to pick first? And that this order is different when it does file writing?

**Comment by retorquere** [comment]
*smacks forehead* yes. On it.

**Comment by retorquere** [comment]
I know there must be tons of duplication in the test, and almost none of the output is verified, but the test suite currently has near-complete coverage if I am to believe the test run.
