### ISSUE TITLE
{\emph{Thunnus thynnus}} should not get nocase

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#4]
currently, 

`title = {{{Atlantic}} bluefin tuna ({\emph{Thunnus thynnus}})}` 

imports to 

`title: '<span class="nocase">Atlantic</span> bluefin tuna (<span class="nocase"><i>Thunnus thynnus</i></span>)'`

but as you'll see if you compile the example below, `{\emph{...}}` doesn't case-protect in BibLaTeX, so semantically it should be translated to just

`title: '<span class="nocase">Atlantic</span> bluefin tuna (<i>Thunnus thynnus</i>)'`

```
\documentclass{article}
\usepackage[
    backend=biber,
    natbib=true,
    url=false, 
    doi=true,
    eprint=false,
    style=apa,
]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}

@String{pub-FRED = "Freds Publishing"}
@String{pub-FRED:adr = "London, UK"}

@Book{cit1,
  author = {R. A. Bert},
  title = {{{Atlantic}} bluefin tuna ({\emph{Thunnus thynnus}})},
  publisher = pub-FRED,
  address = pub-FRED:adr
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

\cite{cit1}

\printbibliography

\end{document}
```

**Comment by johanneswilm** [comment]
Is there any definition of what is legal in terms of these brackets?

How about:

> {        \emph{SomeThing}   }

or

> {\emph{Something} and some more text}

Are all of these legal? And if yes, what should they be translated as?

**Comment by retorquere** [comment]
They're both legal, but the rendered text resulting from them is different. The first of your samples does case-protect, the second does not.

**Comment by retorquere** [comment]
My parser doesn't even try parsing braced blocks to nocase to be honest; it's incredible complicated to predict what will end up being case-protected (for some great fun, see [here](https://github.com/retorquere/zotero-better-bibtex/issues/383) and [here](https://github.com/retorquere/zotero-better-bibtex/issues/541)). In BBT, I add `nocase` at the Bib(La)TeX production stage, not at import. This has the downside that users sometimes need to add `nocase` to keep words lowercased, but the behavior (for better or for worse) is consistent in what it will output in Bib(La)TeX and citeproc-js, who would also otherwise capitalize those words.

**Comment by johanneswilm** [comment]
I see. the idea is to add this at import, and then add UI controls in the bibliography editor so that the end user can mess around with capitalization setup him/herself.

When you say your users need to add this, at what stage are we talking? Is this before or after import? Or after export?

What the examples above it seems as if if only the brace is ignored when it comes directly before a command (no space in-between), then that should solve those example cases.

**Comment by retorquere** [comment]
Looks like it indeed it's specifically `{\<cmd{` that does it, but I have no idea what the actual rules are.

BBT users (but for this case: Zotero users in general, as it would affect non-BibTeX users in the same way) would need to add `nocase` stuff by hand in the UI.

**Comment by johanneswilm** [comment]
> Looks like it indeed it's specifically `{\<cmd{` that does it, but I have no idea what the actual rules are.

Ok, we are programmers but don't have  a clue where to look this up. I have looked through all the manuals there are on biblatex. It doesn't mention this anywhere. I have sent an email to the biblatex maintainers. Hopefully they can say something more.

**Comment by johanneswilm** [comment]
Question posted here: http://tex.stackexchange.com/questions/340461/case-preservation-in-bibtex-biblatex

**Comment by retorquere** [comment]
When more involved biblatex questions come around for BBT we often end up at https://github.com/plk/biblatex, although that usually relates to unexpected edge cases.

**Comment by johanneswilm** [comment]
Ok, I guess this is slightly unexpected, as the manual doesn't mention it (AFAICT), but an answer may be as simple as "yes, that is correct". If we don't get an answer through one of those other avenues, let's try that.

**Comment by johanneswilm** [comment]
@retorquere Ok, so we got an answer, I will try to incorporate that.

Which fields should styling work for? I am thinking of:
* literal fields
* literal lists (in CSL concatenated with join(', '))

But not:
* key fields
* key lists (in CSL concatenated with join(', '))
* uri fields
* verbatim fields

Not sure:

* name lists
I think if styles are allowed in name lists, then only be import for this in some limited sense, as braces are already used to keep the different parts of the name apart.

**Comment by retorquere** [comment]
1. Literal fields/lists: for sure
2. key fields/lists: I don't know what these are
3. uri/verbatim fields: oops, my parser doesn't treat these any different than literals, except for `file` fields (`sentelink` / `file` / `pdf` / `path`) and `url`. The verbatim fields I know are `doi`, `file` (in its various guises), `url`, `eprint`, `eprintclass`, `verb[a-c]`, and none of these would hold markup.
4. name lists: allow markup, because company names can be nuts these days.

**Comment by johanneswilm** [comment]
> key fields/lists: I don't know what these are
origlanguage, editortype, pagination, pubstate, language, etc. .

> name lists: allow markup, because company names can be nuts these days.

Right, is it ok to limit this to literal names (no first/last name)? Do we have to look for ```nocase``` or do all citation systems simply assume that there will be no case changes to names ever?

**Comment by retorquere** [comment]
On the key fields: I don't expect that these'd see markup usage, but my parser treats them as any other field, so markup, if found, will be translated.

I have no knowledge on what the rules are for names, really. Currently my parser supports full parsing there, and in some part depends on it; not necessarily markup, but it will know that `{\emph{Up, up}, { and away}}` is one name, not two, because the `and` is not at the root level of the AST for that string.

On the other hand, I honestly don't expect there to be things like `<i>` in names <sub>([famous last words](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/))</sub>, so parsing markup there should be harmless.

**Comment by johanneswilm** [comment]
Based on thee answer we got, the translation should apparently work this way:
```
\emph{Tinus} -> <nocase><emph>Tinus</emph></nocase>

{\emph{Tinus}} -> <emph>Tinus</emph>

{{\emph{Tinus}}} -> <nocase><emph>Tinus</emph></nocase>
```

This has been added now.

**Comment by retorquere** [comment]
In the case for BibLaTeX, right? Not for BibTeX.

**Comment by johanneswilm** [comment]
In old-school Bibtex you can apparently do this:

```
\emph{\relax Word}
```

And nocase will not be applied to "Word". This does not work in biblatex. But it seems to be more complex than that if you look at the various links they offered in the answers.

**Comment by retorquere** [comment]
Yeah, I generate that (well, a sort-of-equivalent of that) in BibTeX. It's pretty complicated, which is why I didn't bother with it on import. Re-generating bracing on export was easier to get consistently right. Not easy, but easier.

**Comment by retorquere** [comment]
I don't quite follow how the parser works, but will it parse something like `$_\alpha$`?
