### ISSUE TITLE
Parsing JabRef group structure

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#40]
JabRef has a fairly... special format for storing hierarchical structure that I used to parse in the BBT parser. The format isn't especially difficult (but also not especially pretty). Where would be the best entry point to start parsing it? I need that info to replicate (where possible) the hierarchy in Zotero during import.

**Comment by johanneswilm** [comment]
I needed to try it out to see what you were talking about. This is inside of comments at the very end, right?

> @comment{jabref-meta: groupsversion:3;}
>
> @comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:mygroup1\;0\;end_crisis_financiera\;smh080809\;;
}

This should be handled in a comment handler. Currently comemnts are just skipped. You would want to add the call to the comment handler here: https://github.com/fiduswriter/biblatex-csl-converter/blob/master/src/import/biblatex.js#L594 . Depending on how large it turns out to be, I would either have the comment handler be a function only in the biblatex.js file, or create a separate file for it.

**Comment by johanneswilm** [comment]
The question then where you want to store that information. Is group membership something you want to store with each entry? In that case, you'll need to find the corresponding entries. Because the comment is at the absolute end, the entries should already be available as an array under `this.entries`.

**Comment by retorquere** [comment]
I don't really need it in the entry necessarily.

**Comment by johanneswilm** [comment]
I would be fine with adding it to the entry. Like an extra data attribute "group" or "groups" on the relevant entries. But I'm also open to other solutions. Whatever seems most useful to you.

**Comment by retorquere** [comment]
The groups can be nested, and entries can belong to multiple groups. It gets unwieldy fast. I'd just say a nested structure with reference IDs.

**Comment by johanneswilm** [comment]
> The groups can be nested, and entries can belong to multiple groups.

Multiple group shouldn't be much of an issue, as one could simple add an array with group names to each entry. But groups being nested sounds complicated, so you are probably right, and this is better stored somewhere else. Nested structure with reference IDs sounds fine.

Glancing quickly at your code, you are supprting the AllEntriesGroup and ExplicitGroup, but not the Keywordgroup,m correct?

**Comment by johanneswilm** [comment]
I don't think I understand the format of that group logic and what is a subgroup of what. Will be interesting to see your parser.

**Comment by johanneswilm** [comment]
Odd.

Yeah do it whenever. I just updated the expected output for it now so that the tests will parse and I can make another minor point release, so that I can add that new version number as a dependency in FW and continue to develop there.

It's the same issue as yesterday that made the tests not parse. Line endings were `\r\n` instead of `\n`. Any idea what that is about?

**Comment by retorquere** [comment]
No, I thought that was a design decision by you.

Oh wait... ugh, that's probably git doing line-ending translation. Are you
on Windows by any chance?

**Comment by johanneswilm** [comment]
Yes, WIndows 3.1 . Haha. No, I'm on Linux.  Are you on OS X?

The error gets thrown both for me locally (Linux Mint) and on the Travis server (Ubuntu). And TRavis doesn't release to npm unless it runs cleanly.

**Comment by johanneswilm** [comment]
Reading a little more about this[1][2], it seems you are committing with Windows line endings (`\r\n`). For regular line endings, github has ways of dealing with users on different operating systems, but in our case the line ending is encoded in the test output file. So we probably have to add some line handling mechanism ourselves, after agreeing on one of the line-ending standards.

[1] http://digital.ni.com/public.nsf/allkb/5A5A050A3019A573862575F30061D49B
[2] https://help.github.com/articles/dealing-with-line-endings/

**Comment by johanneswilm** [comment]
I opened https://github.com/fiduswriter/biblatex-csl-converter/issues/41

**Comment by retorquere** [comment]
I can't parse the group structure in this parser because it used `\;` as a separator char and these have been replaced before I get to parse the comment.

**Comment by retorquere** [comment]
At the same time I can't assume whitespace is a separator because whitespace is valid in the jabref groups format.

**Comment by johanneswilm** [comment]
How about adding it before the tex replacement starts and simply looking for "@comment{jabref-meta" in the entire input string?

**Comment by johanneswilm** [comment]
What I couldn't figure out was why `}` is allowed in group names, as it would produce this:

```
@comment{jabref-meta: groupsversion:3;}

@comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:small gro}up\;0\;aguilera09\;;
}
```

What I now figured out is that yes, Jabref lets you do that, but it if you try to close and reopen jabref, it is not able to read the group table. Balanced braces in group names are however legal.

**Comment by johanneswilm** [comment]
Another, cleaner, solution would be to only turn the tex string replacement on for individual fields. That's what we had a few days ago. The problem with that was that it was slower by a factor of 10-20 than doing the replacement for the entire document initially.

**Comment by johanneswilm** [comment]
The line that does this is this one:

```
["\\\\;|\\\\hspace\\{0\\.33em\\}", '\u2004'],
```

So it seems we have several options here:
1. You can use a u2004 character as delimiter (not regular space)
2. We can remove this here and add it the particular replacement for `\;` to the literal parser. Most of the very short replacements are there already, and this may be the cleanest solution without leaving the general model we have now.

**Comment by retorquere** [comment]
Oh, u2004 is fine. I sort of do that anyway, but with tabs.

**Comment by johanneswilm** [comment]
Could `\;` also appear in other places (outside of fields? As far as I can tell, it can also be in keys?

**Comment by retorquere** [comment]
I don't know about that. That would seem strange.

It currently sort of works with the break on `\u2004`, but it doesn't find the group info in https://raw.githubusercontent.com/fiduswriter/biblatex-csl-converter/master/test/fixtures/import/Maintain%20the%20JabRef%20group%20and%20subgroup%20structure%20when%20importing%20a%20BibTeX%20db%20%2397.bib

**Comment by retorquere** [comment]
In the other file (Omit URL export when DOI present. #131.prefer-url.biblatex.bib) it does find the groups.

**Comment by johanneswilm** [comment]
Nice solution! But If you rather want to move handling  of `\;` into the lit parser, I'd be fine with that as well.

**Comment by retorquere** [comment]
I think if we also want to parse the group info below it would be required to move handling of both `\;` and `\\` into the lit parser. Otherwise, the current implementation will work.

```
@Comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:new subcoll\;0\;;
2 ExplicitGroup:dee\\\;\\\;{}per\;0\;;
1 ExplicitGroup:deeper\;0\;;
}
```

**Comment by johanneswilm** [comment]
Ok, I've added that. I noticed it also created issues for the file field in one of your examples. 

Btw - should we try to come up with a standard for indentation and se,mi-colons on line endings? I think you do two spaces indentation (I do 4), and semi colons in the test files (I don't use semi-colons at line-endings).

How about we say 2 spaces indentation, but without semi-colons at line endings?

**Comment by retorquere** [comment]
You've just listed my own preferences. I do usually use two spaces, but I tried to keep to using 4 so as not to disturb your existing source. Did I use semi-colons? I usually don't and I prefer not to use them, it's just so much more clutter.
