### ISSUE TITLE
line endings in test files

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/biblatex-csl-converter#41]
On some machines the importer produces output with `\r\n` line endings, on others it produces `\n`. The line endings are part of the test output files, so this goes beyond having common line handling across contributor OSs (which should be standardized through https://github.com/fiduswriter/biblatex-csl-converter/commit/ce02d94a7d2ed1e717e20a2bbd2a046a2b6c150e ).

**Comment by retorquere** [comment]
I'm on OSX, but I'd strongly prefer eol=lf on all text files.

I just ran dos2unix on all my bib files, and there were no changes.

**Comment by retorquere** [comment]
Even after running dos2unix, locally all my tests pass (no changes to the json)

**Comment by johanneswilm** [comment]
And do the tests now fail for you?

**Comment by johanneswilm** [comment]
Maybe something in the way you created the expected test output added the `\r`?

**Comment by retorquere** [comment]
uh yes, now they do. Which is weird, because none of the JSON files contain `\r\n`, and the `.bib` files have gone through dos2unix.

The error formatting is a problem though; the results is just a big wall of text. Do you know if there's a way to make the `test...deepEquals` return something a little more readable?

**Comment by johanneswilm** [comment]
No, not really. It's the first time I try ava.

**Comment by johanneswilm** [comment]
Maybe your node instance is set up to create those line endings. What node version do you run this on? Both me locally and on travis we are on 6.x, I believe.

**Comment by retorquere** [comment]
One of the text files had a mix of `\r\n` and `\n` and it looks like that confused dos2unix. Fixed that and my tests run green again.

**Comment by retorquere** [comment]
I'm on node 7.2.0
