### ISSUE TITLE
A single newline (either \r\n or \n) should be translated to a space

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#42]
In BibTeX, a single newline doesn't render as a line break but as a space. Multiple consecutive line breaks should be preserved though.

**Comment by johanneswilm** [comment]
@retorquere I hope this is as you described:

>1 x '\r\n' => ' '
1 x '\n' => ' '
2 x '\r\n' => 2 x '\n'
2 x '\n' => 2 x '\n'

I also noticed there are some examples of just '\r' in your test material. What should that turn into?

**Comment by retorquere** [comment]
That's indeed what I meant.

I have no idea how a lone `\r` could have gotten into the test files. Those were in references I was handed as a test case. I'd say that should not occur, and having them just turn up in the parsed output is OK. I've removed them from the test files.
