### ISSUE TITLE
separate annotation fields?

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/biblatex-csl-converter#43]
right now we have defined `optional` and `required` fields for each bibtype.

However, the fields `keyword`, `abstract` and `annotations` are not really listed as optional fields in the biblatex manual, as these are fields that allow for annotation functionality for any kind of entry type.

Biblatex also allows for annotation fields per field by using the `+an` suffix (for example `title+an`), and we don't handle those at all right now.

I wonder whether it would be better to handle all of these as a third kind of fields "annotation fields", that are only defined once for all entry types and which additionally automatically include all defined input types with `+an` suffixes for any given type.

On the other hand, the rules for how such annotations are structured seems complex and I'm not sure it is being used much in real-world applications. So maybe that is a bit too much? Do you have any experience with these, @retorquere ?

**Comment by retorquere** [comment]
I see `keyword`, `abstract` and `annotations` quite regularly on import, and I generate them on export, so in that sense I have experience with them. I've never seen the `+an` variant, and I can't generate them as Zotero doesn't store that kind of information.

I think it would be easiest to handle all these fields as "meta-optional", so where you test for

```
                bType['required'].includes(fKey) ||
                bType['optional'].includes(fKey)
```

you could just test for

```
                bType['required'].includes(fKey) ||
                bType['optional'].includes(fKey) ||
                ['keyword, 'abstract', 'annotations', 'note'].indexOf(fKey) >= 0 ||
                fKey.slice(-3) === '+an'
```

**Comment by johanneswilm** [comment]
> you could just test for

Yes, that's similar to what I had in mind, except that I wanted to put the list of annotation fields (keywords, abstract, annotations) into a new variable inside of const.js, the idea being that with time the entire description of all the fields and types can be inside of const.js and be separated from the parsing logic.

> I've never seen the +an variant

Ok, so if we have never seen them, maybe we should just not parse them a lot for now and just provide unparsed versions of them.

**Comment by johanneswilm** [comment]
Btw, `annote` is marked as an alias of `annotation`. But `note` is an entirely different field?

**Comment by retorquere** [comment]
Oh, sure, no issue with putting them in `const.js`. And yes, it would be easy enough to add `+an` fields the first time we encounter them.

`note` is a bibtex field, but I need to be able to parse both biblatex and bibtex. No issue with having `note` in `unexpected` or `unknown`, as long as I can get to the parsed version of it. AAMOF I will very likely just do something like `Object.assign({}, ref.fields, ref.unknown_fields, unexpected_fields)` before I start transforming the reference into a Zotero reference.

**Comment by johanneswilm** [comment]
Actually, I could find the note field also in the biblatex manual. I just wanted to make sure that it is not another alias of the annotation field.  And apparently it isn't. I guess the note is shorter and more likely to show up in the bibliography. The annotation is more more personal and longer.
