### ISSUE TITLE
Support for Cyrillic, Chinese, Arabic, etc.

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/biblatex-csl-converter#44]
Test cases can be found at https://github.com/ORCID/bibtexParseJs/tree/master/test

**Comment by retorquere** [comment]
I've added these test cases -- most seem to parse fine but there's a few problems (you'll see which go red).

As an aside, why do published/location/eprinttype parse to an array of arrays of objects rather than an array of objects?

**Comment by johanneswilm** [comment]
Will investigate.

In the meantime: Did you notice that the names in the Cyrillic version apparently use commas instead of "and" as delimiter? I hope this is simply an error in those test files and that there are not "special rules" when names are in Cyrillic.

**Comment by johanneswilm** [comment]
Hmm, I thought I saw it this morning, but there seems to be "and" in the test files you imported.

**Comment by johanneswilm** [comment]
> As an aside, why do published/location/eprinttype parse to an array of arrays of objects rather than an array of objects?

@retorquere As far as I can tell, in the json output of the testfiles, `howpublished` and `eprinttype` each create an array of objects, which is what would be expected for styled text strings. `location` is defined as a list of styled text strings, so for `location` we would expect an array of arrays of objects.

**Comment by retorquere** [comment]
Location is simply a string field, right? Nothing like author or keywords. So why then the array of arrays? With an array of objects I understand that the objects combine to one logical entity, but I don't know what an array of array means. For author, I get it; each element in the top level array is an author. But what is each logical top level entity in eprinttype or location?

**Comment by johanneswilm** [comment]
> Location is simply a string field, right?

No, biblatex defines `location` as a list of literals with an 'and' delimiter. So you can have `"Tucson, AZ and Oslo, Norway"` so this turns into `["Tucson, AZ", "Oslo, Norway"]`. That accounts for the outer array in the case of `location`. 

Additionally, we have turned test styling on for those three fields. So it can be "\textbf{Oslo}, Norway and \textit{Tucson}, AZ". This then turns into:

```
[
    [{
        type: 'text',
        text: 'Oslo',
        marks: [{
            type: 'strong'
        }]
    }, {
        type: 'text',
        text: ', Norway'
    }],
    [{
        type: 'text',
        text: 'Tucson',
        marks: [{
            type: 'em'
        }]
    }, {
        type: 'text',
        text: ', AZ'
    }]
]
```

So technically all this makes sense. `eprinttype` and `howpublished` Are slightly simpler in that they are not an array of strings, but just a string.

**Comment by retorquere** [comment]
I did not know that about location. But I've seen arrays of arrays in the test results for eprinttype and publication.

**Comment by johanneswilm** [comment]
Do you remember which ones? I checked two files and there they were arrays of objects.

**Comment by retorquere** [comment]
That was `publisher` rather than `publication` and `eprintclass` rather than `eprinttype`; maybe those have the same rules as `location` does. The full set of array-of-arrays I found are:

* `location` in `Wikipedia should parse.json`
* `publisher` in `Wikipedia should parse.json`
* `institution` in `Sorting and optional particle handling #411.on.biblatex.json`
* `eprintclass` in `Square brackets in Publication field (85).bibtex.json`
* `origlocation` in `map csl-json variables #293.biblatex.json`
* `origpublisher` in `map csl-json variables #293.biblatex.json`

**Comment by johanneswilm** [comment]
All of these were correct, except `eprintclass`, which was supposed to be a literal field and not a literal list. I have fixed that.

**Comment by johanneswilm** [comment]
It seems like Chinese, Russian, etc. now parse. @retorquere Btw, what do you do to easily save the current correct test result to file?

I previously temporarily inserted:

```
fs.writeFileSync(expected, JSON.stringify(found, null, 2))
```

But this only makes sense if all failing tests now suddenly work. It doesn't work if one only needs to mark some tests as working.

**Comment by retorquere** [comment]
I do that, copy the one file I need out of that directory, checkout the directory to clear changes, and put that one file back.

**Comment by johanneswilm** [comment]
support has been added
