### ISSUE TITLE
handling of key fields

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/biblatex-csl-converter#45]
Some fields are defined as holding string keys. If I understand the biblatex instructions correctly, the fields can either contain one of the known options, or a random string. What I cannot figure out is if this is true for all these fields, or more for some than others. Also, for some fields there doesn't seem to be a good list specifying which are the "known" keys.

The fields that are defined as key fields are:

`pagination`, `pubstate`, `type`, `authortype`, `bookpagination`, `editortype`, `editoratype`, `editorbtype`, `editorctype`, `origlanguage`.

`language` is defined as a "list of keys". 

For these it's unclear to me what the "known options" are:

`authortype`, `origlanguage`, `language`.

There is also a field `langid`, which only seems to permit the languages listed in table 2, page 26 of http://tug.ctan.org/macros/latex/exptl/biblatex/doc/biblatex.pdf .

What is not clear to me: Are the languages for `langid` the same ones that are the "known keys" for `language` and `origlanguage`? Is `langid` just one value, while `language` allows multiple? Do I just choose one of them?

Any idea, @retorquere ?

**Comment by retorquere** [comment]
I honestly have no idea.

**Comment by johanneswilm** [comment]
@retorquere After reading through an old discussion about this [1], I figured out that the `language` field of biblatex is just a string, whereas the field `langid` is the one that maps to CSLs `language`. 

At the same time, the field `language` in bibtex files many times seems to be used in the same way as the langid field. So I've switched to using langid for the field, while leaving language as just a string. Yet, when the language field happens to consist of one of the languages known to babel, it copies the string into the langid field as well.

Now the question is: If language and origlanguage just are test strings, do they require styling? Same applies to name fields of personal names: Can people's names contain styling, or will that break down biber anyway? (Literal names are set to be able to contain styling).


[1] https://forums.zotero.org/discussion/33960/biblatex-import-export-csl-language-biblatex-langid

**Comment by johanneswilm** [comment]
My research so far:

* Natural names: can contain styling by means of `\mkbibbold{}`

* Language field: Does not accept `\mkbibbold{}`, but does accept `$_2$`. It's not a verbatim field either, so underscore, etc. have to be escaped. The question is whether that is meant as a feature or merely a random bug. I think the safest would be to strip all styling (what's the usecase anyway?), but it would be good if we could classify the field as being A or B.

**Comment by retorquere** [comment]
I'd have to defer to @plk. I have no idea what the rules are.
