### ISSUE TITLE
feature request: accept both ; and , as keyword separators

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#50]
I have entries in my test set (meaning they've been found in the wild) where the keywords are separated by semicolons rather than commas.

**Comment by johanneswilm** [comment]
That sounds good to me as long as it doesn't break anything. There are no examples of keywords that contain ";" characters?

**Comment by retorquere** [comment]
I haven't seen any, but the `keywords` field has no formal format. AAMOF I have one test case where someone had commas in the keywords (for chemical elements IIRC -- I'll find it soon enough) and who wanted to separate on `<comma><space>`, but not `<comma>`. I don't remember how I handled that (probably a postscript), but the keywords field is the wild west of bibtex.

**Comment by johanneswilm** [comment]
To accept commas and semi-colons, this line should be changed to:

`oFields[fKey]` = fValue.split(/[,;]/g).map((string)=>{return string.trim()})`

https://github.com/fiduswriter/biblatex-csl-converter/blob/f1b49490b9894331e2a28fb4785697ef4a2692f4/src/import/biblatex.js#L487

Having commas not work as separators and have spaces make a difference seems to go against the definition used in biblatex:

> A separated list of keywords. These keywords are intended for the bibliographyfilters (see §§3.7.2and 3.12.4), they are usually not printed. Note that with the defaultseparator (comma), spaces around the separator are ignored.

page 27, http://tug.ctan.org/macros/latex/exptl/biblatex/doc/biblatex.pdf

**Comment by retorquere** [comment]
I'm not advocating for the comma-space thing, I was just describing the odd stuff you could find there 😄

**Comment by johanneswilm** [comment]
Ok, try with the line I mentioned above. If that works for your test files, feel free to update and merge it.

**Comment by retorquere** [comment]
How do releases work BTW?

**Comment by retorquere** [comment]
I done gone broke the tests.

**Comment by johanneswilm** [comment]
I forgot. I think we may have set it up to autorelease via travis if the tests go through. I can check it tomorrow if it still hasn't been released. :)

**Comment by retorquere** [comment]
No problem.
