### ISSUE TITLE
information request: pages field

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#51]
When parsing the `pages` field I get this structure:

```
[[[{"type":"text","text":"300"}],[{"type":"text","text":"301"}]]]
```

does that mean "a pages field can occur multiple times, and can be a range"? I didn't know the `pages` field could occur multiple times.

**Comment by johanneswilm** [comment]
I don't think we allow any field more than once, do we?

The innermost `[...]` is there because it can contain styling. The next `[...]` is there because we allow a range of pages. The third level `[...]` is because we allow pages and ranges (plural). See the description in the biblatex PDF: 

> One or more page numbers or page ranges

**Comment by retorquere** [comment]
I didn't think so either, but I was trying to parse this field. Indented, it looks like this:

```
[
  [
    [
      {
        "type": "text",
        "text": "300"
      }
    ],
    [
      {
        "type": "text",
        "text": "301"
      }
    ]
  ]
]
```

So that's a single-element array, containing a two-element array (the range); I had expected a two-element top-level array to designate the range.

**Comment by johanneswilm** [comment]
Right. So for example you could have these values:

"**301**-302, **310**-313"

It's plural "range**s**", right?

**Comment by retorquere** [comment]
Oh, right. I'll have to figure out how to translate that to Zotero (only one `pages` field there). Thanks for the info!

**Comment by johanneswilm** [comment]
Also, one needs to be able to differentiate between: "310, 313" and "310-313".

**Comment by johanneswilm** [comment]
And the pages field in Zotero doesn't allow more than one range? In bibtext it's just one instance of the pages field, but that one field can contain several page ranges, as I understand it.

**Comment by retorquere** [comment]
That looks to be right, and Zotero doesn't really do much itself with the pages field. I'd have to go dive into the CSL processor to see what it does with the field value.

**Comment by johanneswilm** [comment]
Hmm, Just tried out Zotero. For input it seems just to give a simple input field and doesn't really seem to care about what I put into it.

**Comment by retorquere** [comment]
That's Zotero. It leaves most of the interpretation to citeproc (or BBT)
