### ISSUE TITLE
techreport is parsed to thesis

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#55]
```
@techreport{Abbott-2007-aa,
  Address = {Brussels, Belgium},
  Author = {Abbott, Roderick},
  Class = {States & Markets 2009, Diss Tax & Democracy 2010ff},
  Date-Modified = {2014-06-14 15:13:01 +0000},
  Institution = {European Center for International Political Economy},
  Keywords = {Political Economy,Finance, Markets},
  Title = {Are Developing Countries Deterred from Using the WTO Dispute Settlement System? - Participation of Developing Countries in the DSM in the years 1995-2005},
  Year = {2007},
    Local-Zo-Url-1 = {./Abbott-2007-aaa.pdf}
}
```

gets me bib_type `thesis`, I'd have expected either 'techreport' or 'report'.

**Comment by retorquere** [comment]
Would it be possible to expose the raw type in the raw_fields or somesuch?

**Comment by johanneswilm** [comment]
> Would it be possible to expose the raw type in the raw_fields or somesuch?

Maybe, but first I'll try to find out why it's mapped like that. It doesn't seem right.

**Comment by johanneswilm** [comment]
I have fixed the parsing rule. This was clearly an error. As for the type in raw fields -- if you still want that, could you open another issue for that?

**Comment by retorquere** [comment]
Will do. Has the website been updated with the new parser?

**Comment by retorquere** [comment]
Oh I see it has been.

**Comment by johanneswilm** [comment]
Which website?

**Comment by retorquere** [comment]
https://fiduswriter.github.io/biblatex-csl-converter/

**Comment by johanneswilm** [comment]
ah. That also happens automatically as part of the travis process.

**Comment by retorquere** [comment]
A few hiccups aside my port to your parser has already found a few errors in my testcases (meaning errors in my own parser)
