### ISSUE TITLE
Parser uses window.RegExp

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#6]
`window` is not available on all JS environments (such as Node, and FF).

**Comment by johanneswilm** [comment]
Should it maybe just be RegExp? From what I can tell, that does exist. FF = Firefox? I believe Firefox does have window.

**Comment by retorquere** [comment]
Just `RegExp` works. FF = Firefox indeed, but in chrome-JS (where extensions live), you don't (usually) have `window`.

**Comment by johanneswilm** [comment]
Where do these global expressions live then, if there is no window? On node.js there is `global` to store global variables. Is that also where global methods live?

**Comment by retorquere** [comment]
If I just remove `window.` it works for me.
