### ISSUE TITLE
backslashes and curly braces

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#61]
This is of course a synthetic test case, but I had expected this

```
@article{BibTeXEscapeTest1,
  title = {Escaped backslash followed by \{\}: \\{}}
}
```

to have parsed to

```
"Escaped backslash followed by {}: \n"
```
rather than

```
"Escaped backslash followed by \\{\\}: \\\\{}"
```

**Comment by johanneswilm** [comment]
I found this case earlier and found it to look a bit odd. As far as I can tell, there is something wrong with the original syntax. The first two braces seem to be escaped correctly. Then there is a `\\` which looks like an escaped backslash. And then there is `{}` which I don't quite understand what is doing.

Where would the `\n` come from?

**Comment by retorquere** [comment]
I have updated the [MWE](https://www.sharelatex.com/learn/Line_breaks_and_blank_spaces#!#Line_breaks) to show how it renders.

The way I interpreted the above:

1. `\{`/`\}` are literal braces, so I had expected `{`/`}` for that
2. `\\` is a [line break](https://www.sharelatex.com/learn/Line_breaks_and_blank_spaces#!#Line_breakshttps://www.sharelatex.com/learn/Line_breaks_and_blank_spaces#!#Line_breaks), hence the `\n`
3. the `{}` is just an empty LaTeX block, which renders to nothing.

**Comment by johanneswilm** [comment]
The reason it parses it like that is that it arrives at the conclusion that the number of opening and closing non-escaped braces don't match. So it just tries to make a basic conversion.

**Comment by retorquere** [comment]
And for sure it looks odd, you won't find this in the wild :smile:. I just had it to test exactly these three cases.

**Comment by johanneswilm** [comment]
I see. I tried to put `\\` in the title field of an example biblatex file, and it just produced an error when i tried to run biber. Is this only allowed in some fields?

**Comment by retorquere** [comment]
TBH I don't know what bib processor sharelatex uses in that MWE (there's no option in the project settings), but it renders without error there, and I don't know of any instance where `\\` doesn't mean line break. To get a backslash you'd use either `\textbackslash` or `\backslash` depending on whether you are in math mode or not.

**Comment by johanneswilm** [comment]
right. Hmm, i got it to work by running lualatex now.  Ok, so we'll escape that one.

**Comment by retorquere** [comment]
Oh right the MWE uses pdflatex which is a lualatex derivative I think.

**Comment by johanneswilm** [comment]
> and I don't know of any instance where \\ doesn't mean line break

In the file field. It contains '\\\\' in the file path.

**Comment by retorquere** [comment]
Verbatim fields are different, that's right, I forgot about that.

**Comment by johanneswilm** [comment]
Ok, the fact that verbatim fields are different mean that we have to handle all these things not in the beginning but first when parsing the literals.

That meant that we again were back at the issue of unresolvable variables being delimited by `%` signs. Instead I now use `\u0870` - an unused unicode character. This also means that if you want to use the raw_fields, you now have to look for this character instead of `%` to find variables.

**Comment by retorquere** [comment]
That's OK -- I don't inspect the raw fields, I just pass them straight into Zotero for people who want to use Zotero as a faux-JabRef.

I must admit I don't fully understand what you mean by "find variables". I know the `var # " text "` way of "interpolating" variables into the reference but I'm not aware of any other way.

**Comment by johanneswilm** [comment]
Look at the output and the lines with IEEE in rawoutput. I think you'll get it then.

Basically, you asked for undeclared variables to be handled and we do handle them in the normal output. But in rawoutput, where we only output a string, there is no obvious way of delivering such variables.

**Comment by retorquere** [comment]
*right*, OK, I get it. I didn't use to handle that at all -- in raw mode I delivered the raw latex string after var expansion. But I'm reconsidering raw mode TBH (sorry)

**Comment by johanneswilm** [comment]
Let me know if you want it delivered in another format. We have turned raw output off entirely, so it's totally up to you.

**Comment by retorquere** [comment]
I want to apologize for making you spit out raw fields and then not using them. My own parser just parsed bib(la)tex into a json equivalent and I did the parsing to unicode at a later stage; I alway had the same fields, and that made the choice to convert to html-is unicode or not (where "not" was my raw mode) was simpler. Withe the biblatex-csl-converter a lot more is done in the parsing stage and there's no longer the simple one-on-one mapping between raw fields and cooked fields. But I'm bery happy with the parser that's in place now, and I'd drop (or defer) raw mode in BBT before I'd go back to my own parser.

**Comment by johanneswilm** [comment]
That's fine. The raw mode code is really not costing us a lot. If you don't use it, we may just remove the flag for it for now as it's somewhat confusing for others because all the data should almost always be there anyway, if nothing else in unexpected or unknown fields. We can always turn it on again if you have use for it in the future.

**Comment by retorquere** [comment]
Removing it for now is fine by me.

**Comment by johanneswilm** [comment]
ok, and with that v. 0.24 has been released.

**Comment by retorquere** [comment]
Looking good so far. I have one remaining test case that tests the group export -- your parser is unearthing a few errors in my test cases, and some things I could simplify (mostly unicode equivalents for `<sup>2</sup>` and a few others; I expect those to pass, but there's 900+ references to hand-check in that test case, so that will keep me busy for a bit.
