### ISSUE TITLE
Pages range missing data

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#62]
With this reference:

```
@Article{Brahms_1965,
 Pages                    = {C3-32--C3-35}}
```

I get `C3-35` as the range, but `32` isn't in the resulting parse tree.

**Comment by johanneswilm** [comment]
I will take a look at it. I think part of the problem is that some specify ranges like this: {3-5}

**Comment by retorquere** [comment]
Yeah, the references found around the 'net can be a bit of a mess. I think my old parser first checked for `--` and then for `-` as a workaround.

**Comment by johanneswilm** [comment]
Ooh, unfortunately it looks like what you have there is going against the biblatex definition of the range field:

> Range fields consist of one or more ranges where all dashes are normalizedand replaced by the command \bibrangedash. A range is something optionally followed by one or more dashes optionally followed by somenon-dash (e.g.5--7). Any number of consecutive dashes will only yield a single range dash. A typical example of a range field is the pages field. [1]

Valid examples for the pages field are : 

> {55-65}
> {431--456, 791--823} [2]

So the number of dashes doesn't matter. 

Trying this out with your regular bibtex in ShareLaTex, the output of pages gives me:

> pages C3–32–C3–35

All the dashes seem to be of the same length. 

We can still add some mechanism to try to read this, but it seems like this is badly formed bibtex and so for output, we should transform it to something else. Basically, the individual page should not contain any dashes at all.

[1] http://tug.ctan.org/macros/latex/exptl/biblatex/doc/biblatex.pdf p. 14
[2] http://ctan.cs.uu.nl/macros/latex/contrib/biblatex/doc/examples/biblatex-examples.bib

**Comment by johanneswilm** [comment]
Seems to be a problem also in regular bibtex [1].


[1] https://tex.stackexchange.com/questions/174780/compound-page-numbers-with-single-dash

**Comment by johanneswilm** [comment]
This is interesting: BibLaTeXś definition says this is incorrect, but nevertheless, BibLaTeX is able to handle it much better than regular bibtex.
`pages = {C2-34--C3-35, 3-5}`

turns into:

>  pp. C2-34–C3-35, 3–5

**Comment by retorquere** [comment]
Yeah, I mean, this test case isn't synthetic, they're actual references in use I got from BBT users. It strikes me as somewhat odd that page numbers should not be allowed to have dashes -- the (extract from) the sample I had has section-page, and in materials that have that structure, there is no other valid page number. The basic fault here would lie in the term "number" -- they're page identifiers, which are usually, but not always, numbers.

Looks like biblatex uses a similar heuristic as I did previously. Too damn bad that Nick has dropped off the rader -- I'm loathe to go bother plk directly, and he was my proxy towards them.

**Comment by johanneswilm** [comment]
I just tried this:
`pages = {C1-34, C2-34--C3-35, 3-5}`

which returns this in biblatex:

>  pp. C1–34, C2-34–C3-35, 3–5

Biblatex iis able to process the second and third one correctly, but not the first one. And really, I don't think there is any way it could handle that.

**Comment by johanneswilm** [comment]
My patch should bring us on par with biblatex.

**Comment by johanneswilm** [comment]
What I find strange is that there is no builtin command to create a symbol that can be used instead of the dash within the page number. Even in biblatex, it seems I cannot use any alternative utf-8 symbols for this.

**Comment by retorquere** [comment]
I don't think any reference manager gets referencing 100% right TBH -- citeproc is where it's at outside biblatex AFAICT, and there are tons of hacky workarounds in use for things that would be easy to do in biblatex (helped by the fact that latex is actually a programming language -- some things are possible but not wise to do).

This fix you just added makes my test proceed one step further, I'll let you know if I find more -- most work will be to fix my faulty test cases for things my old parser missed.
