### ISSUE TITLE
cedilla

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#64]
```
@Article{Goncalves_2009,
  Author                   = {Gon\c{c}alves, A. M. B. and Campos, L. C. and Ferlauto, A. S. and Lacerda, R. G.}
}
```
 parses to `Gon¸calves` rather than `Gonçalves`

**Comment by retorquere** [comment]
I've added an attempted fix on a branch

**Comment by retorquere** [comment]
Ah, I think you merged before my merging of the two rules made it to the repo. I've tested locally, the order  makes no difference.

**Comment by johanneswilm** [comment]
Ok, weird. I can see your commit, but it looks like it isn't part of anything. Could you push it somewhere again? Maybe directly to master?

**Comment by johanneswilm** [comment]
@retorquere Or how do you suggest we deal with this?

**Comment by retorquere** [comment]
I've re-done the change, tested locally, and pushed to master.

I'm slightly sorry for flooding you with work but I'm having a blast. The port was way easier than I though it would be, my code cleaned up tremendously in the process, and there was a small but significant number of things my old parser didn't catch.

**Comment by johanneswilm** [comment]
very cool! I am very glad myself that we nio longer have to maintain this all by ourselves. Your testing is making the filter much better. With some luck we may even get more than our two projects involved in this.

**Comment by retorquere** [comment]
BTW the test case I am going through now (227 of 912 references vetted... slow going) can never have been an active part of my test suite. There's cases where I have keywords just uppercased in my match file, and I have no idea how that could have happened. They were also out of order. But they do obviously belong together. Very odd.

**Comment by retorquere** [comment]
The core Zotero BibTeX importer could well use this... they're planning a move to Electron, which would bring the use of npm packages into the realm of the possible/obvious.

**Comment by retorquere** [comment]
Or Mendeley.

**Comment by retorquere** [comment]
Or really any of the reference managers that use citeproc-js

**Comment by johanneswilm** [comment]
All true

**Comment by retorquere** [comment]
Although I offered BBT to Mendeley and I got some clueless techsupport response on the order of "what reference is not importing" I am offering to build BibTeX support into Mendeley if you tell me about your API "and you have problems importing this API reference?"

Plus Elsevier 🙄

**Comment by retorquere** [comment]
And BTW all reference manager out in the open except JabRef suck at bibtex (and JabRef is making some odd moves lately TBH).

**Comment by johanneswilm** [comment]
I didn't get the first part. But my experience dealing with big tech companies like that is that the best you can do is to try getting past the tech support and instead engage with the engineers. They may not show their engineers very publicly, but they ae always there somewhere.

**Comment by retorquere** [comment]
I couldn't get a hold of them, and I tried for a bit. I'm well on my way towards a stable BBT for Zotero 5, but for a while it seemed more worthwhile to target something else. The Z5 port is not going to end up in my top X of life experiences.
