### ISSUE TITLE
\# in url field means # rather than \#

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#67]
```
@Article{ck1,
  Url = {http://www.ip-sl.org/procs/abs07.html\#talk9}
}
```

renders the url as `http://www.ip-sl.org/procs/abs07.html#talk9`; currently the parser yields `http://www.ip-sl.org/procs/abs07.html\#talk9`

**Comment by johanneswilm** [comment]
Checking with biblatex, that outputs as

> url: http://www.ip-sl.org/procs/abs07.html%5C#talk9.

The Url field is a verbatim + url-escaped field. Why would one insert a `\` there?

**Comment by retorquere** [comment]
I can't say generally (I just found this in the references in my test set), but if I remove the `\` in the [MWE](https://www.sharelatex.com/project/54feca38f58d781e0c982eeb) I get 

```
You can't use `macro parameter character #' in horizontal mode.)
```

**Comment by johanneswilm** [comment]
I see you are trying t in the sharelatex file. But I wonder: does it really work 100% the same if you use a proper bibtex file and if you create the bibtex file from a latex file the way you do there?

**Comment by retorquere** [comment]
I'll give that a go right now, but Overleaf shows the same behaviour.

**Comment by johanneswilm** [comment]
Overleaf/Sharelatex have merged, AFAIK.

**Comment by johanneswilm** [comment]
Hmm, yes, I get the same result you get with overleaf/sharelatex with the good old natbib.

So basically biblatex and bibtex are incompatible in that regard.

**Comment by johanneswilm** [comment]
The same goes for `%` and I guess all other special latex characters.

**Comment by retorquere** [comment]
I tried this

```
% arara: pdflatex
% arara: bibtex
% arara: pdflatex
% arara: pdflatex
% arara: lmkclean

\documentclass{article}

\usepackage{filecontents}
\usepackage[T1]{fontenc}

\begin{filecontents}{\jobname.bib}
@Article{ck1,
  Url = {http://www.ip-sl.org/procs/abs07.html\#talk9}
}
\end{filecontents}

\begin{document}

 \cite{ck1}

  \H{o} "long Hungarian umlaut (double acute)"
\bibliographystyle{IEEEtran}
\bibliography{\jobname}
\end{document}
```

and ran it using arara and I git the same behavior -- `#` errors out, `\#` does what I expected.

Oh great, so bibtex and biblatex are at odds here. Well I could post-process all `\`s out of URLs in the assumption noone would want them there.

**Comment by johanneswilm** [comment]
> Oh great, so bibtex and biblatex are at odds here. Well I could post-process all \s out of URLs in the assumption noone would want them there.

That is the question. But it seems that Chrome turns any "\" inside a URL into a "/", so the web pages that really do have a "\" in their address will be fairly limited (and they won't get many visitors). So based on that, yes, it seems rather safe for us to remove all "\"-characters from URLs.

**Comment by retorquere** [comment]
Yep, you're right, running this will get the `%5C`

```
% arara: pdflatex
% arara: biber
% arara: pdflatex
% arara: pdflatex
% arara: lmkclean

\documentclass{article}

\usepackage{filecontents}
\usepackage[T1]{fontenc}
\usepackage[backend=biber,style=ieee]{biblatex}

\begin{filecontents}{\jobname.bib}
@Article{ck1,
  Url = {http://www.ip-sl.org/procs/abs07.html\#talk9}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}

 \cite{ck1}

\printbibliography
\end{document}
```

**Comment by johanneswilm** [comment]
Firefox uses `%5C`.

**Comment by retorquere** [comment]
Yeah well people should just not use backslashes in their URLs. Bugger MS for ever getting that annoyance in place.

**Comment by retorquere** [comment]
Oh hey you're already removing them in the parse phase. Cool, I was planning to post-process them.

**Comment by johanneswilm** [comment]
I checked whether there were URLs that had backslashes in them, and then came across the Chrome issue, which effectively means that it's not possible currently to have such URLs [1]. Therefore I thought it cannot do much harm to remove them.

[1] https://stackoverflow.com/questions/10438008/different-behaviours-of-treating-backslash-in-the-url-by-firefox-and-chrome

**Comment by retorquere** [comment]
Nice, that. Bad Chrome.
