### ISSUE TITLE
question: quote handling

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#71]
I have a title that looks like 
```
{``Oxygen diffusion in volume and in grain-boundaries of {Cu$_{2-x}$O}'' in {N}on Stoichiometric...
```
I used to change the quotes to `“` and `”` -- is this something that would be usefu/easy to do in the parser itself? It's easy enough for me to do it post-parse.

**Comment by johanneswilm** [comment]
and the enquote mark should not be applied in these cases?

**Comment by retorquere** [comment]
For sure the author should have used the enquote marks -- but there's a wide varietyin quality of references found around the 'net :smile:

**Comment by johanneswilm** [comment]
right. I mean -- should we try to put enquote marks on this, or will that just create more problems?

**Comment by retorquere** [comment]
Oh, like that. I don't know if we can check that they're balanced, then yeah, that'd be nice.

**Comment by retorquere** [comment]
```
@InBook{Campbell_1968_book,
  Title                    = {``Interdiffusion Coefficients from Conductivity Measurements - {A}pplication to {Cu$_2$O}'' in {M}ass Transport in Oxides},
  Author                   = {Campbell, R. H. and Kass, W. J. and O'Keeffe, M.}
}
```
gets me two enquote blocks. Perhaps I should just do this in post-processing after I've collapsed the parse structure.

**Comment by johanneswilm** [comment]
I think it's handling it correctly. What is the output you get?

**Comment by johanneswilm** [comment]
I found one error - the O is outside the enquote. Wait a second

**Comment by retorquere** [comment]
I'm getting this: https://gist.github.com/anonymous/038db5e982968b6aeccc9f851fb11d86

**Comment by retorquere** [comment]
the `{A}` is getting it's own `enquote` marks for me for example.

**Comment by retorquere** [comment]
Oh wait -- marks aren't nested? Should I interpret consecutive blocks that have the same mark as one bigger block with that mark? That will take some figuring out.

**Comment by johanneswilm** [comment]
That's right because it's still inside the quotation. It's all shown as one flat structure of text nodes with a number of marks. To check whether you should show an end-quote, you will have to check whether the following text node also includes the enquote mark or not.


.... yep, exactly :)

**Comment by johanneswilm** [comment]
Now it's working as it should. There was another minor error not entirely related but in that same string.

This is how all the marks work. You can look at the export filters to see how to turn it into an XML-type structure, if that is what is needed.

**Comment by johanneswilm** [comment]
@retorquere How had you expected for marks to be structured?

**Comment by retorquere** [comment]
I thought they would be nested the same way the bibtex source was. It's not a major issue, certainly not when I can crib from the XML-ish generation from this package. The main thing I have to restructure in my code before kicking that off is where I parse out stuff like `sup`-marked `2`s etc and change them to super/subscript unicode equivs (as per [this table](https://github.com/retorquere/zotero-better-bibtex/blob/import/resource/Better%20BibTeX.coffee#L320)).

**Comment by johanneswilm** [comment]
I see. Yeah, that doesn't look too difficult to do. So basically you convert to these characters IF all of the characters within a sub/sup node can be found in those tables?

**Comment by retorquere** [comment]
No, I break up the `sup` marked text as required.

**Comment by retorquere** [comment]
Is it possible that both sub and sup marks are active?

**Comment by johanneswilm** [comment]
Yes. There is nothing checking for user's stupidity :)

**Comment by retorquere** [comment]
Before I head in and do this, this is not in your current roadmap? To replace `<sup>2</sup>` (even if it occurs in a larger `<sup>` with their unicode lookalikes?

**Comment by johanneswilm** [comment]
I was thinking about this today when I saw your table, but I think in the end I concluded that this wouldn't really be helpful to our users, as they wouldn't have an easy way to input those characters whereas they do have a good way to activate sub and sup (by means of a button in the UI). The fact that it only works with a subset of characters will just make it confusing to edit as well. 

So no, I don't think there is any point in us adding it. But let me know if you need adjustments for you to add it.

**Comment by retorquere** [comment]
It would actually be super helpful if I could access CSLExporter._reformText. I'd just be replicating it otherwise.

**Comment by retorquere** [comment]
Oh wait never mind.

**Comment by johanneswilm** [comment]
Sorry, offline for a while. let me know what needs to be changed so you can do what you need to do.
