### ISSUE TITLE
Diaeresis placed on character before instead of following char

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#75]
```
@Article{Tapiero_1979,
  Title                    = {Conversion photovolta\"ique dans {Cu$_2$O}}
}
```

yields `photovoltäique` rather than `photovoltaïque`

**Comment by retorquere** [comment]
I tried [this](https://gist.github.com/11ff38fa2984d9c17834a9a102144ca5) but it didn't change anything.

**Comment by johanneswilm** [comment]
Nice to see you managed to fix it yourself while I was at dinner :)

**Comment by retorquere** [comment]
I have my moments
