### ISSUE TITLE
Space after key causes parse failure

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#78]
Parsing this

```
@Article{HoSp-87 ,
author = {Hoffmann},
title = {Phase transitions},
}
```

fails; removing the comma after `87` parses successfully

**Comment by retorquere** [comment]
(not to self; corresponding BBT issue @ https://github.com/retorquere/zotero-better-bibtex/issues/716)

**Comment by johanneswilm** [comment]
Interesting. I thought spaces were forbidden there. Does this work with either bibtex or biblatex?

**Comment by retorquere** [comment]
Yes, as far as I can tell (see the [MWE](https://www.sharelatex.com/project/54feca38f58d781e0c982eeb))

**Comment by retorquere** [comment]
Is it OK for me to take a stab at fixing this? It's currently a showstopper for BBT.

**Comment by johanneswilm** [comment]
absolutely. If you don't manage, I will take a look as well.

**Comment by retorquere** [comment]
Where is the entry_key being parsed? Is it [here](https://github.com/fiduswriter/biblatex-csl-converter/blob/master/src/import/biblatex.js#L622)? Is it safe for `this.key` to ignore surrounding whitespace? It's used in many other places.

**Comment by johanneswilm** [comment]
Yes, so it's looking for one of the characters in this list:

https://github.com/fiduswriter/biblatex-csl-converter/blob/master/src/import/biblatex.js#L237

and if `optional===true`, it throws an error if that character is anything else than a comma in 

https://github.com/fiduswriter/biblatex-csl-converter/blob/master/src/import/biblatex.js#L237

I don't remember why we do that :) But to start with, you could try to use `this.key(false)` and see what happens. For some reason we made a check there that there is a comma and not a space right after the key.

**Comment by retorquere** [comment]
this passes the BBT tests but fails one biblatex-csl-converter test

```
diff --git a/src/import/biblatex.js b/src/import/biblatex.js
index 8f62aa4..3596d9b 100644
--- a/src/import/biblatex.js
+++ b/src/import/biblatex.js
@@ -239,7 +239,7 @@ export class BibLatexParser {
                     this.pos = start
                     return null
                 }
-                return this.input.substring(start, this.pos)
+                return this.input.substring(start, this.pos).trim()
             } else {
                 this.pos++
             }
@@ -619,7 +619,7 @@ export class BibLatexParser {
     createNewEntry() {
         this.currentEntry = {
             'bib_type': this.bibType(),
-            'entry_key': this.key(true),
+            'entry_key': this.key(),
             'fields': {}
         }
         this.currentRawFields = {}
```

**Comment by johanneswilm** [comment]
I noticed that the optional was used only for this test. We also want to be able to parse endnote-output, which don't have citation keys at all. With this patch we can have both.

**Comment by retorquere** [comment]
Cool. Do you have an example of such an endnote file? I'd like to add that to my tests. 

Will #78 and #80 be auto-released? I don't know the release process.

**Comment by retorquere** [comment]
Ah, found the test file.

**Comment by johanneswilm** [comment]
It's among the test files. Remember we found a different project that had extended the same basic code? If it didn't come from your original test set, I think that's where it came from. https://github.com/fiduswriter/biblatex-csl-converter/blob/master/test/fixtures/import/Endnote%20should%20parse.bib

**Comment by johanneswilm** [comment]
It looks like I see your messages about 20 messages after you post them.

**Comment by retorquere** [comment]
Got it, added, passes :+1: 

Are we waiting for #79 to release?
