### ISSUE TITLE
Case-protection should only be applied to (English) title fields

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#8]
In this entry, case-protection is applied to the `note` field. Case protection is only in relevant for title fields (and then technically, only for English references)

```
@article{sasson_increasing_2013,
  title = {Increasing cardiopulmonary resuscitation provision in communities with low bystander cardiopulmonary resuscitation rates: a science advisory from the American Heart Association for healthcare providers, policymakers, public health departments, and community leaders},
  volume = {127},
  issn = {1524-4539},
  shorttitle = {Increasing cardiopulmonary resuscitation provision in communities with low bystander cardiopulmonary resuscitation rates},
  doi = {10.1161/CIR.0b013e318288b4dd},
  language = {eng},
  number = {12},
  journal = {Circulation},
  author = {Sasson, Comilla and Meischke, Hendrika and Abella, Benjamin S and Berg, Robert A and Bobrow, Bentley J and Chan, Paul S and Root, Elisabeth Dowling and Heisler, Michele and Levy, Jerrold H and Link, Mark and Masoudi, Frederick and Ong, Marcus and Sayre, Michael R and Rumsfeld, John S and Rea, Thomas D and {American Heart Association Council on Quality of Care and Outcomes Research} and {Emergency Cardiovascular Care Committee} and {Council on Cardiopulmonary, Critical Care, Perioperative and Resuscitation} and {Council on Clinical Cardiology} and {Council on Cardiovascular Surgery and Anesthesia}},
  month = {mar},
  year = {2013},
  note = {{PMID:} 23439512},
  keywords = {Administrative Personnel, American Heart Association, Cardiopulmonary Resuscitation, Community Health Services, Health Personnel, Heart Arrest, Humans, Leadership, Public Health, United States},
  pages = {1342--1350}
}
```

**Comment by johanneswilm** [comment]
Ok, so maybe we need to divide "literal fields" into two categories: One that gets all the styling (title fields) and one that gets all the styling minus "nocase" (all the other ones)?

Which ones would go into the category "title fields"? I assume:

* title
* subtitle
* booktitle
* journaltitle
* journalsubtitle
* maintitle
* mainsubtitle
* origtitle
* reprinttitle
* series
* shortjournal
* shorttitle
* titleaddon
* issuetitle
* issuesubtitle

**Comment by retorquere** [comment]
That looks good to me. 

That still leaves the language issue though. Only English (and its variants) should get it. With no language present, the reference is assumed to be English.

**Comment by johanneswilm** [comment]
And we are 100% that of the 2500 written languages in the world, only English has this capitalization issue?

I was looking a bit at Spanish. On the one hand, Spanish doesn't have the issue if you follow the rules that come out of the academy in Spain. On the other, real-world Spanish issue is heavily influenced by English, including title setting.

But maybe this is some citation convention that has been formally agreed upon by some body?

**Comment by johanneswilm** [comment]
checking for english in the parser should not be that big a problem, if we can make a list of all the strings in the language or langid fields that would indicate English language.

**Comment by retorquere** [comment]
> And we are 100% that of the 2500 written languages in the world, only English has this capitalization issue?

Yes. From the biblatex manual: By default, converting to sentence case is enabled for the following language identifiers: american, british, canadian, english, australian, newzealand as well as the
aliases USenglish and UKenglish. Use \DeclareCaseLangs to extend or change this list.

> I was looking a bit at Spanish. On the one hand, Spanish doesn't have the issue if you follow the rules that come out of the academy in Spain. On the other, real-world Spanish issue is heavily influenced by English, including title setting.

True, but if you mark your reference as non-English, biblatex will just not do any recapitalization. That's just what it does.

> But maybe this is some citation convention that has been formally agreed upon by some body?

Not a clue.

> checking for english in the parser should not be that big a problem, if we can make a list of all the strings in the language or langid fields that would indicate English language.

There's a default list (see above). This list can be amended by the user, but let's not go there.

**Comment by johanneswilm** [comment]
In the case of the note field you mention, what should happen with the braces that would otherwise maintain capitalization? Should they be ignored and removed or ignored and stay?

```
 note = {{PMID:} 23439512},
```

Also, should there be styling in all of these fields?

**Comment by retorquere** [comment]
Ignored, as nocase behavior for biblatex isn't supported for those fields. Semantically, they can't mean nocase. I have no idea why people put them there -- possibly because they misunderstood the capitalization rules and wanted to be sure. Generating them in the output is inert (well technically they could mess with the kerning in some edge cases, so not entirely inert, but usually inert).

When you say styling, you mean markup like `<i>` and such? Yes.

**Comment by johanneswilm** [comment]
Looking at this, I find it slightly odd that there isn't an autoritative list of which fields count as "title fields". I cannot find one anyway. The biblatex sources probably give some insights, but tex isn't my strongest side.

**Comment by retorquere** [comment]
Same here. I few specific users chime in on my issue list from time to time who provide me with latex knowledge.

**Comment by johanneswilm** [comment]
I have looked through the `apa.bbx` that Philip Kime is maintaining. I found these fields to need case preservation sometimes:


> booksubtitle, booktitle, booktitleaddon, eventtitle, mainsubtitle, maintitle, maintitleaddon, origtitle, subtitle, title, titleaddon

I left case preservation on only for the above if one of the languages you mentioned above is in the language field, the language field is missing, or it is empty.

**Comment by johanneswilm** [comment]
@retorquere Let me know if this solves it for you.

**Comment by retorquere** [comment]
Looking good so far
