### ISSUE TITLE
open interval dates

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/biblatex-csl-converter#87]
Hey,
I looked at the biblatex documentation again, and it seems to allow for some date formats that are not EDTF L0/L1 and are marked as incorrect by the checker here: http://digital2.library.unt.edu/edtf/ . One thing is the interval with seasons which you mentioned in the edtf.js issue [1]. Another thing are open intervals ("../1997" or "2014/"). Adding open intervals should not be difficult to add to our own date parser. Downside is that it then moves away from the edtf.js checker. What do you think @retorquere ?

[1] https://github.com/inukshuk/edtf.js/issues/12

**Comment by retorquere** [comment]
My own (sloppy) date parser supports them. From a principled perspective, BCC is a biblatex parser, not an EDTF parser; on a pragmatic level my only concern is whether I can access the data without loss (even if it's been restructured) after it's been parsed do I can import it into Zotero.

**Comment by johanneswilm** [comment]
Good point. So we should probably add those. In that case we could also make that converter try to clean up the date a little bit.

In connection with that, we should probably set `circa` to `true` in CSL output if the date is either approximate or uncertain. But I have not been able to find an example json file with csl contents to see exactly what that should look like. Would it be:

    {
        date-parts: [[2006], [2008]],
        circa: true
    }

**Comment by johanneswilm** [comment]
Btw, should we be using your date parser instead?

**Comment by retorquere** [comment]
> we should probably set circa to true in CSL output if the date is either approximate or uncertain

That's what I do when I generate CSL

> Btw, should we be using your date parser instead?

I don't think so as mine relies on EDTF.js for part of its work :)
