### ISSUE TITLE
package.json pulls in dependencies that (I think) should be devDependencies

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#88]
Currently package.json pulls in

```
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "nearley": "^2.11.1",
    "npm-check-updates": "^2.14.0",
    "randexp": "^0.4.8"
  },
```
It seems to me most of these are devDependencies, and we don't use `nearley` (right?)

**Comment by johanneswilm** [comment]
You are right. I don't think we use randexp either.

**Comment by johanneswilm** [comment]
@retorquere Do you want to fix this? Feel free to clean up other things I missed as well. I don't know what we use babel-polyfill for.

**Comment by retorquere** [comment]
By having them in the dependencies, projects that use BCC will also pull these (plus all their dependencies) in.

**Comment by johanneswilm** [comment]
Right. So probably a good idea to remove them. As for the runtime ones I assume that these get compiled into the final bundles, right?  If that's the case they should also just be buitl dependencies.

**Comment by retorquere** [comment]
I don't know exactly what's used by the package, and I'm especially hesitant to remove anything babel-related. The trouble I had getting babel up and running was one of the reasons why I went with typescript. I'm ok with removing randexp and nearley, but I'd rather just move the babel stuff to devDeps.

**Comment by johanneswilm** [comment]
yeah do that. Other than that, the tests should really show what's going on. 

1. Remove something

2. Run tests

3. If tests are fine - great! Otherwise revert.

There is not much magic in this. The entire rollup setup I only got working through trial and error. I don't understand half of what is going on, really, so if you have a better idea - go right ahead.

**Comment by johanneswilm** [comment]
Did you solve this? @retorquere

**Comment by retorquere** [comment]
Yep.
