### ISSUE TITLE
travis is not running

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/biblatex-csl-converter#92]
Hey @retorquere 
looking at the commit overview page [1], it seems like the first commit that was not verified via travis was your second commit on May 3rd, when you changed around the travis settings. Maybe that's what did it?

[1] https://github.com/fiduswriter/biblatex-csl-converter/commits/master

**Comment by retorquere** [comment]
Should be easy to test - reverting them should then fix it. But these
changes aren't really Travis settings - at worst they could have made the
tests fail, but I don't see how they could have caused tests not to
trigger.

**Comment by johanneswilm** [comment]
has been fixed since
