### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by nise** [fiduswriter/biblatex-csl-converter#96]
I really appreciate tools like this, but some documentation on how to include the module into node.js would be helpful. After setting require('biblatex-csl-converter') it is not clear how to reference BibLatexParser.

**Comment by retorquere** [comment]
I use it like this:

```
import * as biblatex from 'biblatex-csl-converter/src/import/biblatex'

const bib = biblatex.parse(input, {
    processUnexpected: true,
    processUnknown: { comment: 'f_verbatim' },
    processInvalidURIs: true,
  })
```

I think this should also work but I have not tested it:

```
const biblatex = require('biblatex-csl-converter')
const bib = biblatex.parse(input, {
    processUnexpected: true,
    processUnknown: { comment: 'f_verbatim' },
    processInvalidURIs: true,
  })
```

**Comment by nise** [comment]
Thanks for your reply. The latter does not work for me.

**Comment by retorquere** [comment]
[This](https://gist.github.com/33136036075fd512982d436a563c20f9) is what I use to parse my bib files in nodejs.

**Comment by johanneswilm** [comment]
The correct in modern syntax should simply be:

```js
import {BibLatexParser} from 'biblatex-csl-converter'
```

I have added that to the example in the readme. Feel free to create a PR to show how to do it with the legacy `require(...)` method.

**Comment by nise** [comment]
Thank you for the explaination. The following line brought the expected result:

`const biblatex = require('biblatex-csl-converter')
        const bib = biblatex.parse(data, {
            processUnexpected: true,
            processUnknown: { comment: 'f_verbatim' },
            processInvalidURIs: true,
        });
console.log(Object.keys(bib))`
